DROP SEQUENCE LIVESCREEN.ALERT_LEVEL_SEQ;

CREATE SEQUENCE LIVESCREEN.ALERT_LEVEL_SEQ
  START WITH 2802
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  CACHE 200
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM ALERT_LEVEL_SEQ FOR LIVESCREEN.ALERT_LEVEL_SEQ;
