DROP SEQUENCE LIVESCREEN.BROADCASTTIME_SEQ;

CREATE SEQUENCE LIVESCREEN.BROADCASTTIME_SEQ
  START WITH 44949
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 200
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM BROADCASTTIME_SEQ FOR LIVESCREEN.BROADCASTTIME_SEQ;
