DROP SEQUENCE LIVESCREEN.BROADCAST_HIST_SEQ;

CREATE SEQUENCE LIVESCREEN.BROADCAST_HIST_SEQ
  START WITH 110768
  MAXVALUE 999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM BROADCAST_HIST_SEQ FOR LIVESCREEN.BROADCAST_HIST_SEQ;
