DROP SEQUENCE LIVESCREEN.BROADCAST_SCHEDULE_SEQ;

CREATE SEQUENCE LIVESCREEN.BROADCAST_SCHEDULE_SEQ
  START WITH 0
  MAXVALUE 999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM BROADCAST_SCHEDULE_SEQ FOR LIVESCREEN.BROADCAST_SCHEDULE_SEQ;
