DROP SEQUENCE LIVESCREEN.CP_SEQ;

CREATE SEQUENCE LIVESCREEN.CP_SEQ
  START WITH 5612
  MAXVALUE 99999999
  MINVALUE 1
  NOCYCLE
  CACHE 200
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM CP_SEQ FOR LIVESCREEN.CP_SEQ;
