DROP SEQUENCE LIVESCREEN.MTPKG_DISCOUNT_SEQ;

CREATE SEQUENCE LIVESCREEN.MTPKG_DISCOUNT_SEQ
  START WITH 21
  MAXVALUE 9999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_DISCOUNT_SEQ FOR LIVESCREEN.MTPKG_DISCOUNT_SEQ;
