DROP SEQUENCE LIVESCREEN.MTPKG_GROUP_SEQ;

CREATE SEQUENCE LIVESCREEN.MTPKG_GROUP_SEQ
  START WITH 301
  MAXVALUE 999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_GROUP_SEQ FOR LIVESCREEN.MTPKG_GROUP_SEQ;
