DROP SEQUENCE LIVESCREEN.MTPKG_PACKAGE_SEQ;

CREATE SEQUENCE LIVESCREEN.MTPKG_PACKAGE_SEQ
  START WITH 407
  MAXVALUE 9999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_PACKAGE_SEQ FOR LIVESCREEN.MTPKG_PACKAGE_SEQ;
