DROP SEQUENCE LIVESCREEN.MTPKG_RECOVER_REQ_SEQ;

CREATE SEQUENCE LIVESCREEN.MTPKG_RECOVER_REQ_SEQ
  START WITH 1
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_RECOVER_REQ_SEQ FOR LIVESCREEN.MTPKG_RECOVER_REQ_SEQ;
