DROP SEQUENCE LIVESCREEN.PLSQL_PROFILER_RUNNUMBER;

CREATE SEQUENCE LIVESCREEN.PLSQL_PROFILER_RUNNUMBER
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM PLSQL_PROFILER_RUNNUMBER FOR LIVESCREEN.PLSQL_PROFILER_RUNNUMBER;
