DROP SEQUENCE LIVESCREEN.PROMOTION_SEQ;

CREATE SEQUENCE LIVESCREEN.PROMOTION_SEQ
  START WITH 2855
  MAXVALUE 9999999
  MINVALUE 1
  CYCLE
  CACHE 200
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM PROMOTION_SEQ FOR LIVESCREEN.PROMOTION_SEQ;
