DROP SEQUENCE LIVESCREEN.SEQ_LSB_CHARG_HIS;

CREATE SEQUENCE LIVESCREEN.SEQ_LSB_CHARG_HIS
  START WITH 1376645
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 100
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM SEQ_LSB_CHARG_HIS FOR LIVESCREEN.SEQ_LSB_CHARG_HIS;
