DROP SEQUENCE LIVESCREEN.SEQ_LSB_MONTH_COMMAND_REQ;

CREATE SEQUENCE LIVESCREEN.SEQ_LSB_MONTH_COMMAND_REQ
  START WITH 141401
  MAXVALUE 9999999999
  MINVALUE 1
  CYCLE
  CACHE 100
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM SEQ_LSB_MONTH_COMMAND_REQ FOR LIVESCREEN.SEQ_LSB_MONTH_COMMAND_REQ;
