DROP SEQUENCE LIVESCREEN.SYSTEM_RESOURCE_SEQ;

CREATE SEQUENCE LIVESCREEN.SYSTEM_RESOURCE_SEQ
  START WITH 2206905
  MAXVALUE 999999999999999999
  MINVALUE 0
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM SYSTEM_RESOURCE_SEQ FOR LIVESCREEN.SYSTEM_RESOURCE_SEQ;
