DROP SEQUENCE LIVESCREEN.ZONE_CELL_SEQ;

CREATE SEQUENCE LIVESCREEN.ZONE_CELL_SEQ
  START WITH 11005
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM ZONE_CELL_SEQ FOR LIVESCREEN.ZONE_CELL_SEQ;
