DROP SEQUENCE LIVESCREEN.ZONE_SEQ;

CREATE SEQUENCE LIVESCREEN.ZONE_SEQ
  START WITH 348
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM ZONE_SEQ FOR LIVESCREEN.ZONE_SEQ;
