DROP SEQUENCE LIVESCREEN.ZONE_BSC_SEQ;

CREATE SEQUENCE LIVESCREEN.ZONE_BSC_SEQ
  START WITH 2252
  MAXVALUE 999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM ZONE_BSC_SEQ FOR LIVESCREEN.ZONE_BSC_SEQ;
