DROP PROCEDURE LIVESCREEN.JOB_CALL;

CREATE OR REPLACE PROCEDURE LIVESCREEN.job_call AS
 JobNo user_jobs.job%TYPE;
BEGIN
  dbms_job.submit(JobNo, 'MOVE_DATA_PROFILE2_HIST();', SYSDATE,  'SYSDATE + 15/1440');
  dbms_job.submit(JobNo, 'MOVE_DATA_MTPKG_SUBS2_HIS();', SYSDATE,  'SYSDATE + 15/1440');
  COMMIT;
END;
/

CREATE OR REPLACE PUBLIC SYNONYM JOB_CALL FOR LIVESCREEN.JOB_CALL;
