DROP TABLE LIVESCREEN.ACTIVE_DAILY CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ACTIVE_DAILY
(
  TIME   VARCHAR2(12 BYTE),
  TIMES  NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM ACTIVE_DAILY FOR LIVESCREEN.ACTIVE_DAILY;
