DROP TABLE LIVESCREEN.ALARM_LOGS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ALARM_LOGS
(
  PRIORITY     VARCHAR2(5 BYTE),
  TIME_OCCUR   DATE,
  SCOPE_NAME   VARCHAR2(100 BYTE),
  MESSAGE      VARCHAR2(500 BYTE),
  MODULE_NAME  VARCHAR2(20 BYTE),
  TIME_INSERT  DATE                             DEFAULT sysdate
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.ALARM_LOGS.PRIORITY IS 'Hay con goi la level, gom cac gia tri: ERROR, WARN';

COMMENT ON COLUMN LIVESCREEN.ALARM_LOGS.TIME_OCCUR IS 'Thoi gian xay ra su kien';

COMMENT ON COLUMN LIVESCREEN.ALARM_LOGS.SCOPE_NAME IS 'Khoi con cua module MODULE_NAME';

COMMENT ON COLUMN LIVESCREEN.ALARM_LOGS.MESSAGE IS 'Noi dung canh bao';

COMMENT ON COLUMN LIVESCREEN.ALARM_LOGS.MODULE_NAME IS 'Ten module';

COMMENT ON COLUMN LIVESCREEN.ALARM_LOGS.TIME_INSERT IS 'Thoi gian insert vao DB';



CREATE INDEX LIVESCREEN.MODULE_NAME_IDX ON LIVESCREEN.ALARM_LOGS
(MODULE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX LIVESCREEN.PRIORITY_IDX ON LIVESCREEN.ALARM_LOGS
(PRIORITY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX LIVESCREEN.TIME_INSERT_IDX ON LIVESCREEN.ALARM_LOGS
(TIME_INSERT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX LIVESCREEN.TIME_OCCUR_IDX ON LIVESCREEN.ALARM_LOGS
(TIME_OCCUR)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM ALARM_LOGS FOR LIVESCREEN.ALARM_LOGS;
