ALTER TABLE LIVESCREEN.ALARM
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ALARM CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ALARM
(
  ID          NUMBER                            NOT NULL,
  MODULE      VARCHAR2(100 CHAR),
  SUB_MODULE  VARCHAR2(100 CHAR),
  "LEVEL"     VARCHAR2(10 CHAR),
  ALARM_TIME  DATE,
  MESSAGE     VARCHAR2(1000 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.ALARM_PK ON LIVESCREEN.ALARM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.ALARM_TRG 
BEFORE INSERT ON LIVESCREEN.ALARM
FOR EACH ROW
BEGIN
  SELECT ALARM_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM ALARM FOR LIVESCREEN.ALARM;


ALTER TABLE LIVESCREEN.ALARM ADD (
  CONSTRAINT ALARM_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ALARM_PK
  ENABLE VALIDATE);
