ALTER TABLE LIVESCREEN.ALERT_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ALERT_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ALERT_CONFIG
(
  ID              NUMBER(6)                     NOT NULL,
  ALERT_LEVEL_ID  NUMBER(6),
  TYPE_NAME       VARCHAR2(1 BYTE),
  MAX_VALUE       NUMBER(10),
  DURATION        NUMBER(15),
  DESCRIPTION     VARCHAR2(2000 BYTE),
  TIME_CREATED    DATE,
  USER_CREATED    VARCHAR2(100 CHAR),
  STATUS          VARCHAR2(1 BYTE),
  IP              VARCHAR2(15 CHAR),
  MIN_VALUE       NUMBER(10)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.ALERT_CONFIG.TYPE_NAME IS '1:cpu ; 2: ram; 3: memory';

COMMENT ON COLUMN LIVESCREEN.ALERT_CONFIG.STATUS IS '1: active; 0: inactive';



CREATE UNIQUE INDEX LIVESCREEN.ALERT_CONFIG_PK ON LIVESCREEN.ALERT_CONFIG
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.CONTRAINS_IP_TYPE ON LIVESCREEN.ALERT_CONFIG
(TYPE_NAME, IP)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.ALERT_CONFIG_TRG 
 BEFORE
  INSERT
 ON LIVESCREEN.ALERT_CONFIG
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT ALERT_CONFIG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM ALERT_CONFIG FOR LIVESCREEN.ALERT_CONFIG;


ALTER TABLE LIVESCREEN.ALERT_CONFIG ADD (
  CONSTRAINT ALERT_CONFIG_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ALERT_CONFIG_PK
  ENABLE VALIDATE,
  CONSTRAINT CONTRAINS_IP_TYPE
  UNIQUE (TYPE_NAME, IP)
  USING INDEX LIVESCREEN.CONTRAINS_IP_TYPE
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.ALERT_CONFIG ADD (
  CONSTRAINT ALERT_CONFIG_ALERT_LEVEL_FK1 
  FOREIGN KEY (ALERT_LEVEL_ID) 
  REFERENCES LIVESCREEN.ALERT_LEVEL (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
