DROP TABLE LIVESCREEN.ALERT_LEVEL_CHANEL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ALERT_LEVEL_CHANEL
(
  ID         NUMBER(30)                         NOT NULL,
  LEVEL_ID   NUMBER(30)                         NOT NULL,
  CHANEL_ID  NUMBER(30)                         NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM ALERT_LEVEL_CHANEL FOR LIVESCREEN.ALERT_LEVEL_CHANEL;
