ALTER TABLE LIVESCREEN.ALERT_CHANNEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ALERT_CHANNEL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ALERT_CHANNEL
(
  ID            NUMBER(6)                       NOT NULL,
  NAME          VARCHAR2(50 BYTE),
  PHONE         VARCHAR2(30 CHAR),
  EMAIL         VARCHAR2(50 CHAR),
  STATUS        NUMBER(1),
  DESCRIPTION   VARCHAR2(2000 BYTE),
  TIME_CREATED  DATE,
  USER_CREATED  VARCHAR2(100 BYTE),
  TO_CHANEL     NUMBER(4),
  LEVEL_ID      VARCHAR2(200 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.ALERT_CHANNEL.STATUS IS '1: active; 0: inactive';

COMMENT ON COLUMN LIVESCREEN.ALERT_CHANNEL.TO_CHANEL IS '1:sms; 2: email; 3:both';



CREATE UNIQUE INDEX LIVESCREEN.ALERT_CHANNEL_PK ON LIVESCREEN.ALERT_CHANNEL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.ALERT_CHANNEL_TRG 
 BEFORE
  INSERT
 ON LIVESCREEN.ALERT_CHANNEL
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT ALERT_CHANNEL_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM ALERT_CHANNEL FOR LIVESCREEN.ALERT_CHANNEL;


ALTER TABLE LIVESCREEN.ALERT_CHANNEL ADD (
  CONSTRAINT ALERT_CHANNEL_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ALERT_CHANNEL_PK
  ENABLE VALIDATE);
