ALTER TABLE LIVESCREEN.ALERT_LEVEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ALERT_LEVEL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ALERT_LEVEL
(
  ID            NUMBER(6),
  NAME          VARCHAR2(50 BYTE),
  DESCRIPTION   VARCHAR2(2000 BYTE),
  TIME_CREATED  DATE,
  USER_CREATED  VARCHAR2(100 CHAR),
  STATUS        VARCHAR2(1 CHAR),
  TYPE          NUMBER(10)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.ALERT_LEVEL.STATUS IS '0: inactive; 1:active';

COMMENT ON COLUMN LIVESCREEN.ALERT_LEVEL.TYPE IS '1:CPU, 2:RAM, 3: HDD, 4:KPI';



CREATE UNIQUE INDEX LIVESCREEN.ALERT_LEVEL_PK ON LIVESCREEN.ALERT_LEVEL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.CONTRAINS_NAME_TYPE ON LIVESCREEN.ALERT_LEVEL
(NAME, TYPE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM ALERT_LEVEL FOR LIVESCREEN.ALERT_LEVEL;


ALTER TABLE LIVESCREEN.ALERT_LEVEL ADD (
  CONSTRAINT ALERT_LEVEL_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ALERT_LEVEL_PK
  ENABLE VALIDATE,
  CONSTRAINT CONTRAINS_NAME_TYPE
  UNIQUE (NAME, TYPE)
  USING INDEX LIVESCREEN.CONTRAINS_NAME_TYPE
  ENABLE VALIDATE);
