ALTER TABLE LIVESCREEN.AREAS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.AREAS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.AREAS
(
  AREA_ID      NUMBER(30)                       NOT NULL,
  AREANAME     VARCHAR2(50 BYTE)                NOT NULL,
  DESCRIPTONS  VARCHAR2(500 BYTE)               DEFAULT 'Nothing',
  CREATEDDATE  DATE,
  USER_ID      NUMBER(30),
  STATUS       NUMBER(3)                        DEFAULT 1
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.AREAS.STATUS IS '1: active; 0: inactive';



CREATE UNIQUE INDEX LIVESCREEN.AREA_ID ON LIVESCREEN.AREAS
(AREA_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


--  There is no statement for index LIVESCREEN.SYS_C0012654.
--  The object is created when the parent object is created.

CREATE OR REPLACE SYNONYM CBC.AREAS FOR LIVESCREEN.AREAS;


CREATE OR REPLACE PUBLIC SYNONYM AREAS FOR LIVESCREEN.AREAS;


ALTER TABLE LIVESCREEN.AREAS ADD (
  CONSTRAINT AREA_ID
  PRIMARY KEY
  (AREA_ID)
  USING INDEX LIVESCREEN.AREA_ID
  ENABLE VALIDATE,
  UNIQUE (AREANAME)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);
