DROP TABLE LIVESCREEN.BROADCAST_HIST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BROADCAST_HIST
(
  BROADCASTTIME_ID   NUMBER(30)                 NOT NULL,
  PROGRAM_INDEXS     NUMBER(30)                 NOT NULL,
  CP_TOPIC_ID        NUMBER(30)                 NOT NULL,
  ZONE_ID            NUMBER(30)                 NOT NULL,
  STARTTIME          DATE                       NOT NULL,
  STATUS             NUMBER(10)                 NOT NULL,
  CREATEDBY          NUMBER(30),
  CREATEDDATE        DATE,
  SUBCONTENTS        VARCHAR2(1000 CHAR),
  BROADCAST_HIST_ID  NUMBER(30)                 NOT NULL,
  CP_ID              NUMBER(30),
  CP_NAME            VARCHAR2(50 CHAR),
  TOPIC_ID           NUMBER(30),
  TOPIC_NAME         VARCHAR2(50 BYTE),
  PROGRAM_ID         VARCHAR2(50 BYTE),
  SCHEDULE_ID        VARCHAR2(100 CHAR),
  ZONE_NAME          VARCHAR2(20 CHAR)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.BROADCAST_HIST.STATUS IS '0: OK; other: fail';



CREATE OR REPLACE PUBLIC SYNONYM BROADCAST_HIST FOR LIVESCREEN.BROADCAST_HIST;
