ALTER TABLE LIVESCREEN.BROADCAST_CATEGORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.BROADCAST_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BROADCAST_CATEGORY
(
  CATEGORY_ID    NUMBER(15)                     NOT NULL,
  CATEGORY_NAME  VARCHAR2(2000 CHAR),
  PARENT_ID      NUMBER(15),
  DESCRIPTION    VARCHAR2(200 CHAR),
  CREATED_BY     VARCHAR2(200 CHAR),
  CREATED_DATE   DATE,
  UPDATED_BY     VARCHAR2(200 CHAR),
  UPDATED_DATE   DATE
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.BROADCAST_CATEGORY_PK ON LIVESCREEN.BROADCAST_CATEGORY
(CATEGORY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.BROADCAST_CATEGORY_UK1 ON LIVESCREEN.BROADCAST_CATEGORY
(CATEGORY_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.BROADCAST_CATEGORY_TRG BEFORE INSERT ON LIVESCREEN.BROADCAST_CATEGORY 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CATEGORY_ID IS NULL THEN
      SELECT BROADCAST_CATEGORY_SEQ.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM BROADCAST_CATEGORY FOR LIVESCREEN.BROADCAST_CATEGORY;


ALTER TABLE LIVESCREEN.BROADCAST_CATEGORY ADD (
  CONSTRAINT BROADCAST_CATEGORY_PK
  PRIMARY KEY
  (CATEGORY_ID)
  USING INDEX LIVESCREEN.BROADCAST_CATEGORY_PK
  ENABLE VALIDATE,
  CONSTRAINT BROADCAST_CATEGORY_UK1
  UNIQUE (CATEGORY_NAME)
  USING INDEX LIVESCREEN.BROADCAST_CATEGORY_UK1
  ENABLE VALIDATE);
