DROP TABLE LIVESCREEN.BROADCASTTIME_HIST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BROADCASTTIME_HIST
(
  BROADCASTTIME_HIST_ID  NUMBER(30)             NOT NULL,
  BROADCASTTIME_ID       NUMBER(30)             NOT NULL,
  PROGRAM_INDEXS         NUMBER(30)             NOT NULL,
  CP_TOPIC_ID            NUMBER(30)             NOT NULL,
  ZONE_ID                NUMBER(30)             NOT NULL,
  STARTTIME              VARCHAR2(30 CHAR)      NOT NULL,
  STATUS                 NUMBER(10)             NOT NULL,
  CREATEDBY              NUMBER(30),
  CREATEDDATE            DATE,
  ACTIONDATE             DATE,
  ACTION                 VARCHAR2(49 CHAR),
  ACTIONBY               NUMBER(10)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM BROADCASTTIME_HIST FOR LIVESCREEN.BROADCASTTIME_HIST;
