ALTER TABLE LIVESCREEN.BROADCASTTIME
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.BROADCASTTIME CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BROADCASTTIME
(
  BROADCASTTIME_ID  NUMBER(30),
  PROGRAM_INDEXS    NUMBER(30)                  NOT NULL,
  CP_TOPIC_ID       NUMBER(30)                  NOT NULL,
  ZONE_ID           NUMBER(30)                  NOT NULL,
  STARTTIME         VARCHAR2(30 CHAR)           NOT NULL,
  STATUS            NUMBER(10)                  NOT NULL,
  CREATEDBY         NUMBER(30),
  CREATEDDATE       DATE,
  CATEGORY_ID       NUMBER(15),
  SCHEDULE_ID       NUMBER(15)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.BROADCASTTIME.STATUS IS '0: nomal, 5: process, 100 bad content';



CREATE UNIQUE INDEX LIVESCREEN.BROADCASTTIME_PK ON LIVESCREEN.BROADCASTTIME
(BROADCASTTIME_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.BROADCASTTIME_TRG BEFORE INSERT ON LIVESCREEN.BROADCASTTIME 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.BROADCASTTIME_ID IS NULL THEN
      SELECT BROADCASTTIME_SEQ.NEXTVAL INTO :NEW.BROADCASTTIME_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM BROADCASTTIME FOR LIVESCREEN.BROADCASTTIME;


ALTER TABLE LIVESCREEN.BROADCASTTIME ADD (
  CONSTRAINT BROADCASTTIME_PK
  PRIMARY KEY
  (BROADCASTTIME_ID)
  USING INDEX LIVESCREEN.BROADCASTTIME_PK
  ENABLE VALIDATE);
