ALTER TABLE LIVESCREEN.BSC
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.BSC CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BSC
(
  BSC_ID            VARCHAR2(31 BYTE),
  BSC_NAME          VARCHAR2(255 BYTE),
  VERSION           VARCHAR2(63 BYTE),
  PRIMARY_PORT      VARCHAR2(15 BYTE),
  VENDOR            VARCHAR2(63 BYTE),
  PRIMARY_ADDRESS   VARCHAR2(63 BYTE),
  PROTOCOL          VARCHAR2(63 BYTE),
  CENTER            VARCHAR2(255 BYTE),
  INIT_TIME         DATE,
  RECONNECTION_NUM  NUMBER(9),
  DESCRIPTION       VARCHAR2(255 BYTE),
  STATUS            VARCHAR2(15 BYTE),
  USER_ID           NUMBER(7),
  CREATED_DATE      DATE,
  UPDATED_DATE      DATE,
  PROVINCE          VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.BSC_PK ON LIVESCREEN.BSC
(BSC_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM BSC FOR LIVESCREEN.BSC;


ALTER TABLE LIVESCREEN.BSC ADD (
  CONSTRAINT BSC_PK
  PRIMARY KEY
  (BSC_ID)
  USING INDEX LIVESCREEN.BSC_PK
  ENABLE VALIDATE);
