ALTER TABLE LIVESCREEN.BSC_UPDATE_COMMAND
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.BSC_UPDATE_COMMAND CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BSC_UPDATE_COMMAND
(
  ID                 VARCHAR2(100 CHAR)         NOT NULL,
  BSC_ID             VARCHAR2(20 CHAR),
  BSC_NAME           VARCHAR2(50 CHAR),
  TOTAL_CELLS        INTEGER,
  UPDATE_FLAG        NUMBER(1),
  UPDATE_STATUS      VARCHAR2(20 CHAR),
  LAST_UPDATED_TIME  TIMESTAMP(6),
  UPDATED_BY         VARCHAR2(20 CHAR),
  DESCRIPTION        NVARCHAR2(1000),
  SMSCB_SERVER_NAME  VARCHAR2(50 BYTE),
  UPDATE_MODULE      VARCHAR2(20 BYTE),
  SMSCB_CENTER_ID    VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.BSC_UPDATE_SCHEDULE_PK ON LIVESCREEN.BSC_UPDATE_COMMAND
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM BSC_UPDATE_COMMAND FOR LIVESCREEN.BSC_UPDATE_COMMAND;


ALTER TABLE LIVESCREEN.BSC_UPDATE_COMMAND ADD (
  CONSTRAINT BSC_UPDATE_SCHEDULE_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.BSC_UPDATE_SCHEDULE_PK
  ENABLE VALIDATE);
