ALTER TABLE LIVESCREEN.BSC_KPI
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.BSC_KPI CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.BSC_KPI
(
  BSC_ID             VARCHAR2(20 BYTE),
  BSC_NAME           VARCHAR2(50 BYTE),
  ZONE_NAME          VARCHAR2(100 BYTE),
  DATE_TIME          TIMESTAMP(6),
  VENDOR_NAME        VARCHAR2(20 BYTE),
  BROADCASTED        NUMBER,
  FAILED             NUMBER,
  PENDING            NUMBER,
  TOTAL_CELLS        NUMBER(8),
  SUCCESS_CELLS      NUMBER(8),
  FAILURE_CELLS      NUMBER(8),
  PENDING_CELLS      NUMBER(8),
  LAST_UPDATED_TIME  TIMESTAMP(6),
  ID                 VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.BSC_KPI_PK ON LIVESCREEN.BSC_KPI
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM BSC_KPI FOR LIVESCREEN.BSC_KPI;


ALTER TABLE LIVESCREEN.BSC_KPI ADD (
  CONSTRAINT BSC_KPI_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.BSC_KPI_PK
  ENABLE VALIDATE);
