ALTER TABLE LIVESCREEN.CATEGORY_URL_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CATEGORY_URL_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CATEGORY_URL_DETAIL
(
  CATEGORY_ID  NUMBER(15)                       NOT NULL,
  CP_TOPIC_ID  NUMBER(30)                       NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.CATEGORY_URL_DETAIL_PK ON LIVESCREEN.CATEGORY_URL_DETAIL
(CATEGORY_ID, CP_TOPIC_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM CATEGORY_URL_DETAIL FOR LIVESCREEN.CATEGORY_URL_DETAIL;


ALTER TABLE LIVESCREEN.CATEGORY_URL_DETAIL ADD (
  CONSTRAINT CATEGORY_URL_DETAIL_PK
  PRIMARY KEY
  (CATEGORY_ID, CP_TOPIC_ID)
  USING INDEX LIVESCREEN.CATEGORY_URL_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.CATEGORY_URL_DETAIL ADD (
  CONSTRAINT CATEGORY_URL_DETAIL_BROAD_FK1 
  FOREIGN KEY (CATEGORY_ID) 
  REFERENCES LIVESCREEN.BROADCAST_CATEGORY (CATEGORY_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT CATEGORY_URL_DETAIL_CP_TO_FK1 
  FOREIGN KEY (CP_TOPIC_ID) 
  REFERENCES LIVESCREEN.CP_TOPIC (CP_TOPIC_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
