ALTER TABLE LIVESCREEN.CATEGORY_SCHEDULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CATEGORY_SCHEDULE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CATEGORY_SCHEDULE
(
  SCHEDULE_ID        NUMBER(15)                 NOT NULL,
  CATEGORY_ID        NUMBER(15),
  PRIORITY           NUMBER(6),
  START_TIME         DATE,
  END_TIME           DATE,
  INTERVAL           NUMBER(6),
  BREAKING_NEWS      NUMBER(1),
  TIME_TYPE          NUMBER(1),
  TIME_SELECT        VARCHAR2(200 CHAR),
  START_EFFECT_DATE  DATE,
  END_EFFECT_DATE    DATE,
  MAX_AGE            NUMBER(5)                  DEFAULT NULL,
  NUM_OF_SLOTS       NUMBER(5)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.CATEGORY_SCHEDULE.INTERVAL IS 'Khoang cach giua 2 lan lap';

COMMENT ON COLUMN LIVESCREEN.CATEGORY_SCHEDULE.BREAKING_NEWS IS '1: is breaking news. 0: NOT breaking news';

COMMENT ON COLUMN LIVESCREEN.CATEGORY_SCHEDULE.TIME_TYPE IS '0: Date; 1: Week; 2: Month';

COMMENT ON COLUMN LIVESCREEN.CATEGORY_SCHEDULE.TIME_SELECT IS 'Thoi gian chon tuan, thang, cach nhau boi dau , viet lien khong co dau cach 1. Tuan = MON, TUE, WED, THU, FRI, SAT, SUN hoac SUN-SAT 2. Thang = 1-31 hoac 1,2,3';



CREATE UNIQUE INDEX LIVESCREEN.CATEGORY_SCHEDULE_PK ON LIVESCREEN.CATEGORY_SCHEDULE
(SCHEDULE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.CATEGORY_SCHEDULE_TRG BEFORE INSERT ON LIVESCREEN.CATEGORY_SCHEDULE 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM CATEGORY_SCHEDULE FOR LIVESCREEN.CATEGORY_SCHEDULE;


ALTER TABLE LIVESCREEN.CATEGORY_SCHEDULE ADD (
  CONSTRAINT CATEGORY_SCHEDULE_PK
  PRIMARY KEY
  (SCHEDULE_ID)
  USING INDEX LIVESCREEN.CATEGORY_SCHEDULE_PK
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.CATEGORY_SCHEDULE ADD (
  CONSTRAINT CATEGORY_SCHEDULE_BROADCA_FK1 
  FOREIGN KEY (CATEGORY_ID) 
  REFERENCES LIVESCREEN.BROADCAST_CATEGORY (CATEGORY_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
