ALTER TABLE LIVESCREEN.CBC_TRANSACTION_MAP
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CBC_TRANSACTION_MAP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CBC_TRANSACTION_MAP
(
  ID                  NUMBER                    NOT NULL,
  BROADCAST_ID        INTEGER,
  CBC_TRANSACTION_ID  VARCHAR2(20 CHAR),
  TOTAL_CELLS         INTEGER,
  SUCCESS_CELLS       INTEGER,
  FAILURE_CELLS       INTEGER,
  PENDING_CELLS       INTEGER,
  SUCCESS_RATE        FLOAT(126),
  FAILURE_RATE        FLOAT(126),
  PENDING_RATE        FLOAT(126),
  STATUS              VARCHAR2(20 CHAR),
  CREATED_TIME        DATE,
  UPDATED_TIME        DATE
)
TABLESPACE PRO_TOPIC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.CBC_TRANSACTION_MAP_PK ON LIVESCREEN.CBC_TRANSACTION_MAP
(ID)
LOGGING
TABLESPACE PRO_TOPIC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.CBC_TRANSACTION_MAP_TRG BEFORE INSERT ON LIVESCREEN.CBC_TRANSACTION_MAP
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT CBC_TRANSACTION_MAP_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM CBC_TRANSACTION_MAP FOR LIVESCREEN.CBC_TRANSACTION_MAP;


ALTER TABLE LIVESCREEN.CBC_TRANSACTION_MAP ADD (
  CONSTRAINT CBC_TRANSACTION_MAP_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.CBC_TRANSACTION_MAP_PK
  ENABLE VALIDATE);
