ALTER TABLE LIVESCREEN.CELL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CELL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CELL
(
  CELL_KEY           VARCHAR2(63 BYTE),
  BSC_ID             VARCHAR2(31 BYTE)          NOT NULL,
  CELL_NAME          VARCHAR2(255 BYTE)         NOT NULL,
  CELL_ID            VARCHAR2(31 BYTE)          NOT NULL,
  LAC                VARCHAR2(31 BYTE)          NOT NULL,
  GATEWAY_ID         VARCHAR2(15 BYTE),
  MCC                VARCHAR2(15 BYTE),
  MNC                VARCHAR2(15 BYTE),
  STATUS_DECRIPTION  VARCHAR2(255 BYTE),
  STATUS             VARCHAR2(15 BYTE),
  DESCRIPTION        VARCHAR2(255 BYTE),
  USER_ID            NUMBER(7),
  CREATED_DATE       DATE,
  UPDATED_DATE       DATE,
  LONGITUDE          NUMBER,
  LATITUDE           NUMBER,
  RADIUS             NUMBER,
  SHAPE              VARCHAR2(255 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.CELL_PK ON LIVESCREEN.CELL
(CELL_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM CELL FOR LIVESCREEN.CELL;


ALTER TABLE LIVESCREEN.CELL ADD (
  CONSTRAINT CELL_PK
  PRIMARY KEY
  (CELL_KEY)
  USING INDEX LIVESCREEN.CELL_PK
  ENABLE VALIDATE);
