DROP TABLE LIVESCREEN.CELTICK_PKG_DEF CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CELTICK_PKG_DEF
(
  ID                      NUMBER,
  NAME                    VARCHAR2(200 BYTE),
  DESCRIPTION             VARCHAR2(200 BYTE),
  STATUS                  NUMBER,
  PKGID                   NUMBER,
  REGCODE                 VARCHAR2(200 BYTE),
  UNREGCODE               VARCHAR2(200 BYTE),
  DELTYPEID               NUMBER,
  ADMINSERVICETYPEID      NUMBER,
  FREEDAYS                VARCHAR2(100 BYTE),
  SBILLDATE               VARCHAR2(100 BYTE),
  MSGINDEX                VARCHAR2(50 BYTE),
  WELCOMETEXT             VARCHAR2(4000 BYTE),
  USENOTIFICATION         NUMBER,
  NOTIFICATIONTEXT        VARCHAR2(500 BYTE),
  NOTIFICATIONTIME        VARCHAR2(50 BYTE),
  NOTIFICATIONFREQUENCY   NUMBER,
  EXPIRATIONDATE          VARCHAR2(100 BYTE),
  NOTIFICATIONSTARTFROM   NUMBER,
  SENDGREETINGMSG         NUMBER,
  USEBILLRETRIES          NUMBER,
  EXTERNALID              VARCHAR2(200 BYTE),
  EXPIRATIONDAYSAFTERREG  VARCHAR2(100 BYTE),
  SENDGOODBYEMSG          NUMBER,
  GOODBYEMSG              VARCHAR2(4000 BYTE),
  SENDHOLDMSG             NUMBER,
  HOLDMSG                 VARCHAR2(50 BYTE),
  SENDUNHOLDMSG           VARCHAR2(50 BYTE),
  UNHOLDMSG               VARCHAR2(50 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
