DROP TABLE LIVESCREEN.CELTIC_USER_PKG CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CELTIC_USER_PKG
(
  ID             NUMBER,
  MSISDN         VARCHAR2(50 BYTE),
  PKGINSTID      NUMBER,
  PKGSTATUS      NUMBER,
  BILLSTATUS     NUMBER,
  BILLTYPE       NUMBER,
  TOTBILL        NUMBER,
  REGTIME        VARCHAR2(100 BYTE),
  DEREGTIME      VARCHAR2(100 BYTE),
  DEREGBY        VARCHAR2(20 BYTE),
  TOTALSENT      NUMBER,
  MSGINDEX       NUMBER,
  LASTSENTTIME   VARCHAR2(200 BYTE),
  BILLTIME       VARCHAR2(100 BYTE),
  NEXTBILLTIME   VARCHAR2(100 BYTE),
  REGIONID       NUMBER,
  BILLFAILURES   NUMBER,
  RENEWALS       VARCHAR2(50 BYTE),
  FIRSTFAILBILL  VARCHAR2(100 BYTE),
  SMSCID         VARCHAR2(20 BYTE),
  EXTERNALID     VARCHAR2(100 BYTE),
  LASTREVENUE    NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
