DROP TABLE LIVESCREEN.CELTICK_USER_BROADCAST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CELTICK_USER_BROADCAST
(
  PHONENUMBER             VARCHAR2(100 BYTE),
  REASON                  VARCHAR2(100 BYTE),
  CLICKMILES              VARCHAR2(20 BYTE),
  PERIODICALCLICKMILES    VARCHAR2(50 BYTE),
  ACTIVE                  VARCHAR2(20 BYTE),
  ACTIVEUPDATETIME        VARCHAR2(50 BYTE),
  IMEIUPDATETIME          VARCHAR2(50 BYTE),
  COMPANIONVERSION        VARCHAR2(50 BYTE),
  ACTIVATIONSETBY         VARCHAR2(20 BYTE),
  SMSCID                  VARCHAR2(20 BYTE),
  FIRSTREGISTRATIONTIME   VARCHAR2(50 BYTE),
  DELETED                 VARCHAR2(20 BYTE),
  IMEI                    VARCHAR2(50 BYTE),
  OPERATIONALAPPLICATION  VARCHAR2(30 BYTE),
  SCOMPANIONVERSION       VARCHAR2(20 BYTE),
  REGIONID                VARCHAR2(20 BYTE),
  NEEDSIMEIUPDATE         VARCHAR2(20 BYTE),
  LASTCLICK               VARCHAR2(50 BYTE),
  SIMVALUE                VARCHAR2(20 BYTE),
  IMEICOUNT               VARCHAR2(20 BYTE),
  SDRTIME                 VARCHAR2(50 BYTE),
  FIRSTCLICK              VARCHAR2(50 BYTE),
  TOTALSIMVALUE           VARCHAR2(20 BYTE),
  FIRSTACTIVATIONTIME     VARCHAR2(50 BYTE),
  CBCHANNEL               VARCHAR2(20 BYTE),
  CLICKMILESUPDATETIME    VARCHAR2(50 BYTE),
  CI                      VARCHAR2(20 BYTE),
  LAC                     VARCHAR2(20 BYTE),
  BSCID                   VARCHAR2(20 BYTE),
  LASTLOCATIONUPDATETIME  VARCHAR2(50 BYTE),
  CONTENTCATEGORY         VARCHAR2(50 BYTE),
  SUBSCRIPTIONTYPE        VARCHAR2(20 BYTE),
  LIVECHANNELS            VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
