ALTER TABLE LIVESCREEN.CHARGE_HIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CHARGE_HIST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CHARGE_HIST
(
  ID            NUMBER                          NOT NULL,
  MDN           VARCHAR2(20 BYTE),
  CHARGETIME    DATE                            DEFAULT sysdate,
  AMOUNT        NUMBER,
  CHARGERESULT  NUMBER,
  CHARGETYPE    VARCHAR2(20 BYTE),
  SUBTYPE       NUMBER,
  CHARGEDESC    VARCHAR2(200 BYTE),
  RESULT_IN     NUMBER,
  PKGD_ID       VARCHAR2(127 BYTE),
  RESERVE01     VARCHAR2(100 BYTE),
  RESERVE02     VARCHAR2(100 BYTE),
  RESERVE03     VARCHAR2(100 BYTE),
  RESERVE04     VARCHAR2(100 BYTE),
  RESERVE05     VARCHAR2(100 BYTE)
)
TABLESPACE BILL
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.CHARGETIME IS 'Thoi gian tru cuoc';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.AMOUNT IS 'So tien can tru';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.CHARGERESULT IS 'Ket qua tru cuoc dua theo ma loi trong class CHARGE_RESP.CHARGE_RESULT';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.CHARGETYPE IS 'ACTIVE; RECURRENT(MONTHLY)';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.SUBTYPE IS 'Tham khao class CHARGE_RESP.SUB_TYPE: 1 = PREPAID; 2 = POSTPAID';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.CHARGEDESC IS 'Mo ta';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.RESULT_IN IS 'Ma loi tu IN tra ve. Tham khao class CHARGE_RESP.IN_RESULT: 0 = SUCCESS; 401: ACCOUNT_BALANCE_ISNOTENOUGH; 405 = MSISDN_CHANGED_OWNER; 501 = MSISDN_HASNOT_REGISTERED';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.RESERVE01 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.RESERVE02 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.RESERVE03 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.RESERVE04 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CHARGE_HIST.RESERVE05 IS 'Chua su dung';



CREATE UNIQUE INDEX LIVESCREEN.CHARGE_HIST_PK_20121208 ON LIVESCREEN.CHARGE_HIST
(ID)
LOGGING
TABLESPACE BILL_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM CHARGE_HIST FOR LIVESCREEN.CHARGE_HIST;


ALTER TABLE LIVESCREEN.CHARGE_HIST ADD (
  CONSTRAINT CHARGE_HIST_PK_20121208
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.CHARGE_HIST_PK_20121208
  ENABLE VALIDATE);
