DROP TABLE LIVESCREEN.CHARGE_HIST_TEMP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CHARGE_HIST_TEMP
(
  ID            NUMBER                          NOT NULL,
  MDN           VARCHAR2(20 BYTE),
  CHARGETIME    DATE                            DEFAULT sysdate,
  AMOUNT        NUMBER,
  CHARGERESULT  NUMBER,
  CHARGETYPE    VARCHAR2(20 BYTE),
  SUBTYPE       NUMBER,
  CHARGEDESC    VARCHAR2(200 BYTE),
  RESULT_IN     NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
