DROP TABLE LIVESCREEN.CHARGING CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CHARGING
(
  SEQ     NUMBER(10),
  MDN     VARCHAR2(12 BYTE),
  AMOUNT  NUMBER(10,1)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
