DROP TABLE LIVESCREEN.CONFIG_SUBTOPIC CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CONFIG_SUBTOPIC
(
  ID           NUMBER,
  TOPIC_NAME   VARCHAR2(200 BYTE),
  CREATEDDATE  DATE,
  CODE         VARCHAR2(20 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
