ALTER TABLE LIVESCREEN.CONFIG_PARAMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CONFIG_PARAMS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CONFIG_PARAMS
(
  KEY    VARCHAR2(200 BYTE)                     NOT NULL,
  VALUE  VARCHAR2(500 BYTE)                     NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.PRIMAKEY ON LIVESCREEN.CONFIG_PARAMS
(KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM CONFIG_PARAMS FOR LIVESCREEN.CONFIG_PARAMS;


ALTER TABLE LIVESCREEN.CONFIG_PARAMS ADD (
  CONSTRAINT PRIMAKEY
  PRIMARY KEY
  (KEY)
  USING INDEX LIVESCREEN.PRIMAKEY
  ENABLE VALIDATE);
