ALTER TABLE LIVESCREEN.CP
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CP
(
  CP_ID          NUMBER(30)                     NOT NULL,
  CPNAME         VARCHAR2(50 CHAR)              NOT NULL,
  CPDESCRIPTION  VARCHAR2(500 CHAR),
  CPSTATUS       NUMBER(5)                      NOT NULL,
  CREATEDBY      NUMBER(30)                     NOT NULL,
  CREATEDDATE    DATE                           NOT NULL,
  MODIFIEDBY     NUMBER(30),
  MODIFIEDDATE   DATE,
  SHORT_CODE     VARCHAR2(20 BYTE)              NOT NULL,
  CP_CODE        VARCHAR2(100 BYTE),
  RESERVE01      VARCHAR2(100 BYTE),
  RESERVE02      VARCHAR2(100 BYTE),
  RESERVE03      VARCHAR2(100 BYTE),
  RESERVE04      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.CP.SHORT_CODE IS 'VASC = 9144; BLUESEA = 9244';

COMMENT ON COLUMN LIVESCREEN.CP.CP_CODE IS 'VMS goi la CP ID dung de doi soat cuoc va lam key ma hoa goi tin media';

COMMENT ON COLUMN LIVESCREEN.CP.RESERVE01 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CP.RESERVE02 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CP.RESERVE03 IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.CP.RESERVE04 IS 'Chua su dung';



CREATE UNIQUE INDEX LIVESCREEN.TBLCP_PRIMARY ON LIVESCREEN.CP
(CP_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM CP FOR LIVESCREEN.CP;


ALTER TABLE LIVESCREEN.CP ADD (
  CONSTRAINT TBLCP_PRIMARY
  PRIMARY KEY
  (CP_ID)
  USING INDEX LIVESCREEN.TBLCP_PRIMARY
  ENABLE VALIDATE);
