ALTER TABLE LIVESCREEN.CP_SHORTCODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CP_SHORTCODE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CP_SHORTCODE
(
  CP_SHORTCODE_ID  NUMBER(30)                   NOT NULL,
  CP_ID            NUMBER(30)                   NOT NULL,
  SHORT_CODE       VARCHAR2(20 BYTE),
  PRICE            NUMBER(10,1)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.CP_SHORTCODE_PK ON LIVESCREEN.CP_SHORTCODE
(CP_SHORTCODE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.CP_SHORTCODE_U01 ON LIVESCREEN.CP_SHORTCODE
(CP_ID, SHORT_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.TRG_CP_SHORTCODE
 BEFORE 
 INSERT
 ON LIVESCREEN.CP_SHORTCODE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.CP_SHORTCODE_ID := CP_SHORTCODE_SEQ.nextval;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM CP_SHORTCODE FOR LIVESCREEN.CP_SHORTCODE;


ALTER TABLE LIVESCREEN.CP_SHORTCODE ADD (
  CONSTRAINT CP_SHORTCODE_PK
  PRIMARY KEY
  (CP_SHORTCODE_ID)
  USING INDEX LIVESCREEN.CP_SHORTCODE_PK
  ENABLE VALIDATE,
  CONSTRAINT CP_SHORTCODE_U01
  UNIQUE (CP_ID, SHORT_CODE)
  USING INDEX LIVESCREEN.CP_SHORTCODE_U01
  ENABLE VALIDATE);
