ALTER TABLE LIVESCREEN.CP_TOPIC
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.CP_TOPIC CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.CP_TOPIC
(
  CP_TOPIC_ID           NUMBER(30),
  CP_ID                 NUMBER(30)              NOT NULL,
  TOPIC_ID              NUMBER(30),
  URL                   VARCHAR2(500 CHAR)      NOT NULL,
  DATE_PLUG             DATE,
  TIME                  VARCHAR2(20 CHAR),
  AMOUNTS               NUMBER(20),
  REPEATS               NUMBER(10),
  ISTIME                NUMBER(5),
  STATUS                NUMBER(10)              NOT NULL,
  CREATEDBY             NUMBER(30),
  CREATEDDATE           DATE,
  IS_APPROVE            NUMBER(5)               DEFAULT 1,
  TYPE                  NUMBER(5)               DEFAULT 0,
  UPDATETIME            DATE,
  LAST_CONTENTS         VARCHAR2(3999 CHAR),
  LAST_CONTENTS_CRC32   LONG,
  LAST_DOWNLOAD_RESULT  VARCHAR2(3999 CHAR),
  LAST_DOWNLOAD_TIME    DATE,
  SUB_TOPIC_NAME        VARCHAR2(100 BYTE)      DEFAULT 'Default',
  TIME_TYPE             NUMBER                  DEFAULT 0,
  TIME_SELECT           VARCHAR2(1000 BYTE),
  SUBTOPIC_ID           NUMBER                  DEFAULT NULL,
  PRIORITY              NUMBER                  DEFAULT 0
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.ISTIME IS '0: time; 1: date';

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.STATUS IS '0: Ready; 1: Not Ready';

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.IS_APPROVE IS '0: Not Approved; 1: Approved';

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.TYPE IS '0:regular, 1:Game';

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.TIME_TYPE IS '0: Date; 1: Week; 2: Month';

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.TIME_SELECT IS 'Thoi gian chon tuan, thang, cach nhau boi dau , viet lien khong co dau cach 1. Tuan = MON, TUE, WED, THU, FRI, SAT, SUN hoac SUN-SAT 2. Thang = 1-31 hoac 1,2,3';

COMMENT ON COLUMN LIVESCREEN.CP_TOPIC.PRIORITY IS 'Do uu tien: -1 phai phat, 0 ko uu tien, 1,2,3,4,5';



CREATE UNIQUE INDEX LIVESCREEN.CP_TOPIC_PK ON LIVESCREEN.CP_TOPIC
(CP_TOPIC_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM CP_TOPIC FOR LIVESCREEN.CP_TOPIC;


ALTER TABLE LIVESCREEN.CP_TOPIC ADD (
  CONSTRAINT CP_TOPIC_PK
  PRIMARY KEY
  (CP_TOPIC_ID)
  USING INDEX LIVESCREEN.CP_TOPIC_PK
  ENABLE VALIDATE);
