DROP TABLE LIVESCREEN.DAILY_CHANGE_PROFILE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.DAILY_CHANGE_PROFILE
(
  TIME      VARCHAR2(10 BYTE),
  ACTIVE    NUMBER,
  DEACTIVE  NUMBER,
  COS       NUMBER,
  COT       NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM DAILY_CHANGE_PROFILE FOR LIVESCREEN.DAILY_CHANGE_PROFILE;
