DROP TABLE LIVESCREEN.ET$001E00CD0001 CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ET$001E00CD0001
(
  CP_TOPIC_ID           NUMBER(30),
  CP_ID                 NUMBER(30),
  TOPIC_ID              NUMBER(30),
  URL                   VARCHAR2(500 CHAR),
  DATE_PLUG             DATE,
  TIME                  VARCHAR2(20 CHAR),
  AMOUNTS               NUMBER(20),
  REPEATS               NUMBER(10),
  ISTIME                NUMBER(5),
  STATUS                NUMBER(10),
  CREATEDBY             NUMBER(30),
  CREATEDDATE           DATE,
  IS_APPROVE            NUMBER(5),
  TYPE                  NUMBER(5),
  UPDATETIME            DATE,
  LAST_CONTENTS         VARCHAR2(3999 CHAR),
  SUB_TOPIC_NAME        VARCHAR2(100 BYTE),
  LAST_DOWNLOAD_RESULT  VARCHAR2(3999 CHAR),
  LAST_DOWNLOAD_TIME    DATE,
  TIME_TYPE             NUMBER,
  TIME_SELECT           VARCHAR2(1000 BYTE),
  SUBTOPIC_ID           NUMBER,
  PRIORITY              NUMBER,
  LAST_CONTENTS_CRC32   CLOB
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_DATAPUMP
     DEFAULT DIRECTORY DATA_PUMP_DIR
     ACCESS PARAMETERS 
       ( DEBUG = (0 , 0) DATAPUMP INTERNAL TABLE "LIVESCREEN"."CP_TOPIC"  JOB ( "LIVESCREEN","SYS_IMPORT_TABLE_01",5) WORKERID 1 PARALLEL 1 VERSION '11.2.0.0.0' ENCRYPTPASSWORDISNULL  COMPRESSION DISABLED  ENCRYPTION DISABLED  )
     LOCATION (DATA_PUMP_DIR:'bogus.dat')
  )
REJECT LIMIT UNLIMITED
NOPARALLEL
NOMONITORING;
