ALTER TABLE LIVESCREEN.FILTERED_PROGRAM
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.FILTERED_PROGRAM CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.FILTERED_PROGRAM
(
  ID               VARCHAR2(100 CHAR),
  BROADCAST_TIME   TIMESTAMP(6),
  CP_TOPIC_ID      NUMBER,
  ZONE_NAME        VARCHAR2(100 CHAR),
  SUBCONTENT       VARCHAR2(1000 CHAR),
  MENU_TITLE       VARCHAR2(100 CHAR),
  MATCHED_KEYWORD  VARCHAR2(100 CHAR)
)
TABLESPACE TBS_KPI
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.FILTERED_PROGRAM_PK ON LIVESCREEN.FILTERED_PROGRAM
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM FILTERED_PROGRAM FOR LIVESCREEN.FILTERED_PROGRAM;


ALTER TABLE LIVESCREEN.FILTERED_PROGRAM ADD (
  CONSTRAINT FILTERED_PROGRAM_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.FILTERED_PROGRAM_PK
  ENABLE VALIDATE);
