DROP TABLE LIVESCREEN.IMEI_ADVANCED_FILTER CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.IMEI_ADVANCED_FILTER
(
  IMEI    VARCHAR2(20 BYTE)                     NOT NULL,
  STATUS  NUMBER                                NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.IMEI_ADVANCED_FILTER.STATUS IS '0: disable, 1: enable';



CREATE OR REPLACE PUBLIC SYNONYM IMEI_ADVANCED_FILTER FOR LIVESCREEN.IMEI_ADVANCED_FILTER;
