ALTER TABLE LIVESCREEN.IMEI_FILTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.IMEI_FILTER CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.IMEI_FILTER
(
  IMEI    VARCHAR2(20 BYTE)                     NOT NULL,
  STATUS  NUMBER                                NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.IMEI_FILTER.STATUS IS '0: disable, 1: enable';



CREATE UNIQUE INDEX LIVESCREEN.PR_IMEI_FILTER ON LIVESCREEN.IMEI_FILTER
(IMEI)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM IMEI_FILTER FOR LIVESCREEN.IMEI_FILTER;


ALTER TABLE LIVESCREEN.IMEI_FILTER ADD (
  CONSTRAINT PR_IMEI_FILTER
  PRIMARY KEY
  (IMEI)
  USING INDEX LIVESCREEN.PR_IMEI_FILTER
  ENABLE VALIDATE);
