DROP TABLE LIVESCREEN.IMEI_HANDSET CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.IMEI_HANDSET
(
  MODEL                      VARCHAR2(50 BYTE),
  TYPE                       VARCHAR2(20 BYTE),
  CBDD                       VARCHAR2(20 BYTE),
  LIVESCREEN                 VARCHAR2(20 BYTE),
  WAP_TYPES                  VARCHAR2(100 BYTE),
  NOTIFICATION               VARCHAR2(20 BYTE),
  UNICODE_FREE_TEXT          VARCHAR2(20 BYTE),
  IMEI_MECHANISM             VARCHAR2(20 BYTE),
  MMS                        VARCHAR2(20 BYTE),
  USSD                       VARCHAR2(20 BYTE),
  COMMENTS                   VARCHAR2(20 BYTE),
  TEXT_ICON                  VARCHAR2(20 BYTE),
  MENU_ICON                  VARCHAR2(20 BYTE),
  DISP_MODE                  VARCHAR2(20 BYTE),
  IMEI                       VARCHAR2(30 BYTE),
  VENDOR                     VARCHAR2(30 BYTE),
  HANDSET_SPECIFIC_CHANNELS  VARCHAR2(50 BYTE),
  MODEL_VENDOR               VARCHAR2(50 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM IMEI_HANDSET FOR LIVESCREEN.IMEI_HANDSET;
