DROP TABLE LIVESCREEN.IP_VNP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.IP_VNP
(
  IP_NAME      VARCHAR2(20 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(200 BYTE),
  STATUS       NUMBER                           DEFAULT 1                     NOT NULL,
  ID           NUMBER(20)                       NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.IP_VNP.STATUS IS '0 INACTIVE, 1 ACTIVE';



CREATE UNIQUE INDEX LIVESCREEN.IP ON LIVESCREEN.IP_VNP
(IP_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM IP_VNP FOR LIVESCREEN.IP_VNP;


ALTER TABLE LIVESCREEN.IP_VNP ADD (
  CONSTRAINT IP
  UNIQUE (IP_NAME)
  USING INDEX LIVESCREEN.IP
  ENABLE VALIDATE);
