DROP TABLE LIVESCREEN.KEYWORD_FILTER CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.KEYWORD_FILTER
(
  KEYWORD  VARCHAR2(500 BYTE),
  STATUS   NUMBER                               DEFAULT 0
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.KEYWORD_FILTER.STATUS IS '0: disable, 1: enable';



CREATE OR REPLACE PUBLIC SYNONYM KEYWORD_FILTER FOR LIVESCREEN.KEYWORD_FILTER;
