ALTER TABLE LIVESCREEN.KPI_BSC
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.KPI_BSC CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.KPI_BSC
(
  ID                 VARCHAR2(100 CHAR)         NOT NULL,
  BSC_ID             VARCHAR2(31 BYTE),
  SMSCB_CENTER_ID    VARCHAR2(20 CHAR),
  TOTAL_CELLS        NUMBER(9),
  SUCCESS_CELLS      NUMBER(9),
  KPI                NUMBER(5,10),
  LAST_UPDATED_TIME  TIMESTAMP(6),
  INTERVAL           NUMBER(9),
  KPI_TYPE           VARCHAR2(20 CHAR)          DEFAULT 'Normal',
  START_TIME         TIMESTAMP(6),
  END_TIME           TIMESTAMP(6)
)
TABLESPACE TBS_KPI
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.KPI_BSC.KPI_TYPE IS '''Normal'': KPI doi soat. ''Service'': kpi dich vu';



CREATE UNIQUE INDEX LIVESCREEN.KPI_BSC_PK ON LIVESCREEN.KPI_BSC
(ID)
LOGGING
TABLESPACE TBS_KPI
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM KPI_BSC FOR LIVESCREEN.KPI_BSC;


ALTER TABLE LIVESCREEN.KPI_BSC ADD (
  CONSTRAINT KPI_BSC_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.KPI_BSC_PK
  ENABLE VALIDATE);
