DROP TABLE LIVESCREEN.LOG_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LOG_TRANSACTION
(
  ID        NUMBER,
  USERNAME  VARCHAR2(200 BYTE),
  TIME      DATE,
  ACTION    VARCHAR2(500 BYTE),
  CONTENT   VARCHAR2(1000 BYTE),
  FULLNAME  VARCHAR2(400 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM LOG_TRANSACTION FOR LIVESCREEN.LOG_TRANSACTION;
