DROP TABLE LIVESCREEN.LSB_MONTH_COMMAND_REQ CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LSB_MONTH_COMMAND_REQ
(
  ID           NUMBER(12),
  MSISDN       VARCHAR2(20 BYTE),
  COMMAND      NUMBER(3),
  SOURCE_REQ   VARCHAR2(10 BYTE),
  STATE        NUMBER(3),
  LAST_UPDATE  DATE,
  PRIORITY     NUMBER(1)
)
TABLESPACE LSB
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.LSB_MONTH_COMMAND_REQ.COMMAND IS '0: suspend, 3: khoi phuc, 50: no cuoc, 501: huy sim, 405: doi chu, 55: nhac no';

COMMENT ON COLUMN LIVESCREEN.LSB_MONTH_COMMAND_REQ.STATE IS '1: Chua x? lý, 2: Ðang x? lý, 3: X? lý xong';

COMMENT ON COLUMN LIVESCREEN.LSB_MONTH_COMMAND_REQ.LAST_UPDATE IS 'Order theo th?i gian các yêu c?u du?c th?c hi?n b?i Monthly_Ext Java Module';

COMMENT ON COLUMN LIVESCREEN.LSB_MONTH_COMMAND_REQ.PRIORITY IS 'M?c uu tiên x? lý yêu c?u';



CREATE OR REPLACE PUBLIC SYNONYM LSB_MONTH_COMMAND_REQ FOR LIVESCREEN.LSB_MONTH_COMMAND_REQ;
