ALTER TABLE LIVESCREEN.LSB_BILL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.LSB_BILL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LSB_BILL
(
  MSISDN           VARCHAR2(20 BYTE)            NOT NULL,
  LAST_DATE_CHARG  DATE,
  STATUS           NUMBER(2)                    DEFAULT 0,
  STATE_CHARG      NUMBER(2),
  SUB_TYPE         NUMBER(2),
  DATA_PART        NUMBER(2),
  CHARG_FEE        NUMBER(10)                   DEFAULT 0
)
TABLESPACE LSB
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX LIVESCREEN.IDX_BILL_DATA_PART ON LIVESCREEN.LSB_BILL
(DATA_PART)
LOGGING
TABLESPACE LSB_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.IDX_BILL_PK ON LIVESCREEN.LSB_BILL
(MSISDN)
LOGGING
TABLESPACE LSB_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM LSB_BILL FOR LIVESCREEN.LSB_BILL;


ALTER TABLE LIVESCREEN.LSB_BILL ADD (
  CONSTRAINT IDX_BILL_PK
  PRIMARY KEY
  (MSISDN)
  USING INDEX LIVESCREEN.IDX_BILL_PK
  ENABLE VALIDATE);
