DROP TABLE LIVESCREEN.LSB_RECHARGE_WAIT_RESP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LSB_RECHARGE_WAIT_RESP
(
  MSISDN       VARCHAR2(20 BYTE),
  LAST_UPDATE  DATE
)
TABLESPACE LSB
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM LSB_RECHARGE_WAIT_RESP FOR LIVESCREEN.LSB_RECHARGE_WAIT_RESP;
