ALTER TABLE LIVESCREEN.LSB_DISCOUNT_BILLING
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.LSB_DISCOUNT_BILLING CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LSB_DISCOUNT_BILLING
(
  ID            NUMBER                          NOT NULL,
  STARTTIME     DATE,
  ENDTIME       DATE,
  DISCOUNT      NUMBER,
  RATEDISCOUNT  NUMBER,
  MSISDN        NVARCHAR2(20),
  DISCOUNTTYPE  NUMBER(2)
)
TABLESPACE LSB
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.LSB_DISCOUNT_BILLING.DISCOUNTTYPE IS '1: ACTIVE; 2: MONTHLY';



CREATE UNIQUE INDEX LIVESCREEN.IDX_DISCOUNT_BILLING_PK ON LIVESCREEN.LSB_DISCOUNT_BILLING
(ID)
LOGGING
TABLESPACE LSB_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.TRIG_BI_DISCOUNT 
 BEFORE 
 INSERT
 ON LIVESCREEN.LSB_DISCOUNT_BILLING
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
begin
if inserting then
    if :NEW."ID" is null then
        select SEQUENCE_INDEX.nextval into :NEW."ID" from dual;
    end if;
end if;
end;
/


CREATE OR REPLACE PUBLIC SYNONYM LSB_DISCOUNT_BILLING FOR LIVESCREEN.LSB_DISCOUNT_BILLING;


ALTER TABLE LIVESCREEN.LSB_DISCOUNT_BILLING ADD (
  CONSTRAINT IDX_DISCOUNT_BILLING_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.IDX_DISCOUNT_BILLING_PK
  ENABLE VALIDATE);
