ALTER TABLE LIVESCREEN.LSB_SERVICE_FEE_BILLING
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.LSB_SERVICE_FEE_BILLING CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LSB_SERVICE_FEE_BILLING
(
  ID           NUMBER                           NOT NULL,
  STARTTIME    DATE                             NOT NULL,
  ENDTIME      DATE                             NOT NULL,
  AMOUNT       NUMBER                           NOT NULL,
  SERVICETYPE  NUMBER,
  COS_ID       VARCHAR2(20 BYTE)
)
TABLESPACE LSB
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.LSB_SERVICE_FEE_BILLING.SERVICETYPE IS '1: ACTIVE; 2: MONTHLY';



CREATE UNIQUE INDEX LIVESCREEN.IDX_SERVICE_FEE_BILLING_PK ON LIVESCREEN.LSB_SERVICE_FEE_BILLING
(ID)
LOGGING
TABLESPACE LSB_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM LSB_SERVICE_FEE_BILLING FOR LIVESCREEN.LSB_SERVICE_FEE_BILLING;


ALTER TABLE LIVESCREEN.LSB_SERVICE_FEE_BILLING ADD (
  CONSTRAINT IDX_SERVICE_FEE_BILLING_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.IDX_SERVICE_FEE_BILLING_PK
  ENABLE VALIDATE);
