ALTER TABLE LIVESCREEN.LSB_CHARGE_REQUEST
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.LSB_CHARGE_REQUEST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.LSB_CHARGE_REQUEST
(
  MSISDN    VARCHAR2(30 CHAR)                   NOT NULL,
  DATE_REQ  DATE,
  STATE     NUMBER(2)                           DEFAULT 0,
  REQ_ID    NUMBER(10)                          NOT NULL
)
TABLESPACE LSB
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.LSB_CHARGE_REQUEST.STATE IS '0: Yêu c?u KP m?i, Job RECHARGE_PROCESS chua ti?p nh?n x? lý yêu c?u
1: Job RECHARGE_PROCESS ti?p nh?n x? lý yêu c?u';



CREATE UNIQUE INDEX LIVESCREEN.IDX_CHARGE_REQUEST_PK ON LIVESCREEN.LSB_CHARGE_REQUEST
(REQ_ID)
LOGGING
TABLESPACE LSB_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM LSB_CHARGE_REQUEST FOR LIVESCREEN.LSB_CHARGE_REQUEST;


ALTER TABLE LIVESCREEN.LSB_CHARGE_REQUEST ADD (
  CONSTRAINT IDX_CHARGE_REQUEST_PK
  PRIMARY KEY
  (REQ_ID)
  USING INDEX LIVESCREEN.IDX_CHARGE_REQUEST_PK
  ENABLE VALIDATE);
