DROP TABLE LIVESCREEN.MENU_ITEMS_DEFAULT CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MENU_ITEMS_DEFAULT
(
  MENUITEMS_ID  VARCHAR2(50 BYTE)               NOT NULL,
  PARENT_ID     VARCHAR2(50 BYTE)               NOT NULL,
  ACTIONTYPE    VARCHAR2(100 BYTE),
  SYNTAX        VARCHAR2(100 BYTE),
  CONTENT       VARCHAR2(3000 BYTE),
  SHORTCODE     VARCHAR2(100 BYTE),
  LEVELS        NUMBER(10),
  TITLE         VARCHAR2(1000 BYTE),
  PROGRAM_ID    VARCHAR2(50 BYTE)               DEFAULT 1                     NOT NULL,
  INDEXS        NUMBER(30)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM MENU_ITEMS_DEFAULT FOR LIVESCREEN.MENU_ITEMS_DEFAULT;
