ALTER TABLE LIVESCREEN.MENU_ITEMS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MENU_ITEMS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MENU_ITEMS
(
  MENUITEMS_ID  VARCHAR2(50 BYTE)               NOT NULL,
  PARENT_ID     VARCHAR2(50 BYTE)               NOT NULL,
  ACTIONTYPE    VARCHAR2(100 BYTE),
  SYNTAX        VARCHAR2(100 BYTE),
  CONTENT       VARCHAR2(3000 BYTE),
  SHORTCODE     VARCHAR2(100 BYTE),
  LEVELS        NUMBER(10),
  TITLE         VARCHAR2(1000 BYTE),
  PROGRAM_ID    VARCHAR2(50 BYTE)               DEFAULT 1                     NOT NULL,
  INDEXS        NUMBER(30),
  INSERT_TIME   DATE                            DEFAULT sysdate
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MENU_ITEMS.ACTIONTYPE IS 'sms, smsdd, ussd, voice, wap, launchHttpUrl';

COMMENT ON COLUMN LIVESCREEN.MENU_ITEMS.SYNTAX IS 'ServiceKey';

COMMENT ON COLUMN LIVESCREEN.MENU_ITEMS.SHORTCODE IS 'ServiceAddress';

COMMENT ON COLUMN LIVESCREEN.MENU_ITEMS.INSERT_TIME IS 'Thoi gian insert program vao DB';



CREATE OR REPLACE PUBLIC SYNONYM MENU_ITEMS FOR LIVESCREEN.MENU_ITEMS;


ALTER TABLE LIVESCREEN.MENU_ITEMS ADD (
  CONSTRAINT MENU_ITEMS_PK
  PRIMARY KEY
  (MENUITEMS_ID)
  DISABLE NOVALIDATE);
