ALTER TABLE LIVESCREEN.MODULE_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MODULE_STATUS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MODULE_STATUS
(
  ID                  NUMBER(6)                 NOT NULL,
  NAME                VARCHAR2(50 CHAR)         NOT NULL,
  STATUS              NUMBER(1),
  MAX_QUEUE_SIZE      NUMBER(15),
  CURRENT_QUEUE_SIZE  NUMBER(15),
  LAST_UPDATE_TIME    DATE                      NOT NULL,
  DESCRIPTION         NVARCHAR2(2000)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MODULE_STATUS.STATUS IS '0: Active ; 1: Inactive';



CREATE UNIQUE INDEX LIVESCREEN.MODULE_STATUS_PK ON LIVESCREEN.MODULE_STATUS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.MODULE_STATUS_UK1 ON LIVESCREEN.MODULE_STATUS
(NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MODULE_STATUS_TRG 
BEFORE INSERT ON LIVESCREEN.MODULE_STATUS
FOR EACH ROW
DISABLE
BEGIN
  SELECT MODULE_STATUS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM MODULE_STATUS FOR LIVESCREEN.MODULE_STATUS;


ALTER TABLE LIVESCREEN.MODULE_STATUS ADD (
  CONSTRAINT MODULE_STATUS_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.MODULE_STATUS_PK
  ENABLE VALIDATE,
  CONSTRAINT MODULE_STATUS_UK1
  UNIQUE (NAME)
  USING INDEX LIVESCREEN.MODULE_STATUS_UK1
  ENABLE VALIDATE);
