DROP TABLE LIVESCREEN.MONTHLY_SHORTCODE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MONTHLY_SHORTCODE
(
  TIME       VARCHAR2(10 BYTE),
  SHORTCODE  VARCHAR2(20 BYTE),
  TOTAL      NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM MONTHLY_SHORTCODE FOR LIVESCREEN.MONTHLY_SHORTCODE;
