ALTER TABLE LIVESCREEN.MSISDN_FILTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MSISDN_FILTER CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MSISDN_FILTER
(
  MSISDN  VARCHAR2(20 BYTE)                     NOT NULL,
  STATUS  NUMBER                                DEFAULT 1                     NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MSISDN_FILTER.STATUS IS '0: disable, 1: enable';



CREATE UNIQUE INDEX LIVESCREEN.PR_MSISDN_FILTER ON LIVESCREEN.MSISDN_FILTER
(MSISDN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM MSISDN_FILTER FOR LIVESCREEN.MSISDN_FILTER;


ALTER TABLE LIVESCREEN.MSISDN_FILTER ADD (
  CONSTRAINT PR_MSISDN_FILTER
  PRIMARY KEY
  (MSISDN)
  USING INDEX LIVESCREEN.PR_MSISDN_FILTER
  ENABLE VALIDATE);
