DROP TABLE LIVESCREEN.MSISDN_FILTER_BAK_20140730 CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MSISDN_FILTER_BAK_20140730
(
  MSISDN  VARCHAR2(20 BYTE)                     NOT NULL,
  STATUS  NUMBER                                NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
