ALTER TABLE LIVESCREEN.MTPKG_GROUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_GROUP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_GROUP
(
  GROUP_ID     NUMBER(7),
  GROUP_NAME   NVARCHAR2(255),
  DESCRIPTION  NVARCHAR2(255),
  PARENT_ID    NUMBER(7),
  LEVELS       NUMBER(3),
  GROUP_CODE   NVARCHAR2(255)
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.MT_PKG_GROUP_PK ON LIVESCREEN.MTPKG_GROUP
(GROUP_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_GROUP_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_GROUP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PKG_ID
  :new.GROUP_ID := MTPKG_GROUP_SEQ.nextval;
END MTPKG_GROUP_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_GROUP FOR LIVESCREEN.MTPKG_GROUP;


ALTER TABLE LIVESCREEN.MTPKG_GROUP ADD (
  CONSTRAINT MT_PKG_GROUP_PK
  PRIMARY KEY
  (GROUP_ID)
  USING INDEX LIVESCREEN.MT_PKG_GROUP_PK
  ENABLE VALIDATE);
