DROP TABLE LIVESCREEN.MTPKG_MESSAGE_HIS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_MESSAGE_HIS
(
  MSISDN        VARCHAR2(15 BYTE)               NOT NULL,
  ID            NUMBER(31),
  STATUS        NUMBER(1)                       NOT NULL,
  RESP_TYPE     VARCHAR2(15 BYTE),
  SEND_TIME     DATE                            NOT NULL,
  SENT_TIME     DATE,
  CONTENT       VARCHAR2(3071 BYTE)             NOT NULL,
  PRIORITY      NUMBER(1),
  ERROR_CODE    NUMBER(10),
  MESSAGE_ID    VARCHAR2(100 BYTE),
  DATA_PART     NUMBER(6),
  ERROR_DETAIL  VARCHAR2(255 BYTE),
  PKGD_ID       VARCHAR2(127 BYTE),
  INSERT_TIME   DATE                            DEFAULT sysdate
)
NOCOMPRESS 
TABLESPACE MTPKG_MESSAGE_HIS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARTITION BY RANGE (DATA_PART)
(  
  PARTITION P201307 VALUES LESS THAN (201308)
    LOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_MESSAGE_HIS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
)
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_HIS.RESP_TYPE IS 'SMS; MEDIA';



CREATE OR REPLACE PUBLIC SYNONYM MTPKG_MESSAGE_HIS FOR LIVESCREEN.MTPKG_MESSAGE_HIS;
