ALTER TABLE LIVESCREEN.MTPKG_SCHEDULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_SCHEDULE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_SCHEDULE
(
  PKGD_ID      VARCHAR2(127 BYTE)               NOT NULL,
  SEND_TIME    DATE                             NOT NULL,
  SCHEDULE_ID  NUMBER,
  IS_INTERVAL  NUMBER(1),
  STATUS       NUMBER(1)                        DEFAULT 1,
  TIME_TYPE    NUMBER,
  TIME_SELECT  VARCHAR2(1000 BYTE)
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_SCHEDULE.IS_INTERVAL IS 'Lap lich phat tin nay hang ngay khong? --- 0: Ko; 1: Phat hang ngay;';

COMMENT ON COLUMN LIVESCREEN.MTPKG_SCHEDULE.STATUS IS '0: On; 1: Off;';

COMMENT ON COLUMN LIVESCREEN.MTPKG_SCHEDULE.TIME_TYPE IS '0: daily, 1:weekly, 2:Monthly';

COMMENT ON COLUMN LIVESCREEN.MTPKG_SCHEDULE.TIME_SELECT IS 'SUN,MON,TUE,WED,THU,FRI,SAT....';



CREATE UNIQUE INDEX LIVESCREEN.MTPKG_SCHEDULE_PK ON LIVESCREEN.MTPKG_SCHEDULE
(SCHEDULE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_SCHEDULE_TRG     before insert ON LIVESCREEN.MTPKG_SCHEDULE    for each row
begin     if inserting then       if :NEW."SCHEDULE_ID" is null then          select MTPKG_SCHEDULE_SEQ.nextval into :NEW."SCHEDULE_ID" from dual;       end if;    end if; end;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_SCHEDULE FOR LIVESCREEN.MTPKG_SCHEDULE;


ALTER TABLE LIVESCREEN.MTPKG_SCHEDULE ADD (
  CONSTRAINT MTPKG_SCHEDULE_PK
  PRIMARY KEY
  (SCHEDULE_ID)
  USING INDEX LIVESCREEN.MTPKG_SCHEDULE_PK
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.MTPKG_SCHEDULE ADD (
  CONSTRAINT MTPKG_SCHEDULE_FK1 
  FOREIGN KEY (PKGD_ID) 
  REFERENCES LIVESCREEN.MTPKG_PACKAGE_DETAIL (PKGD_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
