DROP TABLE LIVESCREEN.MTPKG_TMP_FEE_DISCOUNT CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE LIVESCREEN.MTPKG_TMP_FEE_DISCOUNT
(
  PKGD_ID              VARCHAR2(127 BYTE)       NOT NULL,
  CHARG_TYPE           NUMBER(1)                NOT NULL,
  FEE_START_TIME       DATE                     NOT NULL,
  FEE_END_TIME         DATE                     NOT NULL,
  DISCOUNT_START_TIME  DATE,
  DISCOUNT_END_TIME    DATE,
  MSISDNS              VARCHAR2(15 BYTE),
  CHARG_FEE            NUMBER
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_TMP_FEE_DISCOUNT FOR LIVESCREEN.MTPKG_TMP_FEE_DISCOUNT;
