DROP TABLE LIVESCREEN.MTPKG_RECOVER_WAIT CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_RECOVER_WAIT
(
  MSISDN       VARCHAR2(15 BYTE),
  LAST_UPDATE  DATE,
  PKGD_ID      VARCHAR2(127 BYTE)
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_RECOVER_WAIT.PKGD_ID IS 'De phan biet Khoi phuc Goi tin nao???';



CREATE OR REPLACE PUBLIC SYNONYM MTPKG_RECOVER_WAIT FOR LIVESCREEN.MTPKG_RECOVER_WAIT;
