DROP TABLE LIVESCREEN.MTPKG_BILL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_BILL
(
  MSISDN               VARCHAR2(15 BYTE),
  PKGD_ID              VARCHAR2(127 BYTE),
  NEXT_CHARG_TIME      DATE,
  DATA_PART            NUMBER(2),
  SUB_DATA_PART        NUMBER(2),
  CHARG_FEE            NUMBER(10,3),
  LAST_UPDATE          DATE,
  INSERTED_EXTEND_MSG  NUMBER(1),
  IS_PROVISIONED       NUMBER(1)                DEFAULT 0,
  EXPIRED_TIME         DATE
)
NOCOMPRESS 
TABLESPACE MTPKG_BILL
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
PARTITION BY RANGE (DATA_PART)
SUBPARTITION BY RANGE (SUB_DATA_PART)
(  
  PARTITION P1 VALUES LESS THAN (2)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P1_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P1_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P2 VALUES LESS THAN (3)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P2_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P2_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P3 VALUES LESS THAN (4)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P3_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P3_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P4 VALUES LESS THAN (5)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P4_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P4_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P5 VALUES LESS THAN (6)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P5_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P5_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P6 VALUES LESS THAN (7)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P6_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P6_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P7 VALUES LESS THAN (8)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P7_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P7_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P8 VALUES LESS THAN (9)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P8_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P8_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P9 VALUES LESS THAN (10)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P9_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P9_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P10 VALUES LESS THAN (11)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P10_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P10_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P11 VALUES LESS THAN (12)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P11_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P11_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P12 VALUES LESS THAN (13)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P12_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P12_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P13 VALUES LESS THAN (14)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P13_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P13_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P14 VALUES LESS THAN (15)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P14_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P14_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P15 VALUES LESS THAN (16)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P15_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P15_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P16 VALUES LESS THAN (17)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P16_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P16_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P17 VALUES LESS THAN (18)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P17_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P17_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P18 VALUES LESS THAN (19)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P18_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P18_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P19 VALUES LESS THAN (20)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P19_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P19_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P20 VALUES LESS THAN (21)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P20_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P20_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P21 VALUES LESS THAN (22)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P21_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P21_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P22 VALUES LESS THAN (23)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P22_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P22_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P23 VALUES LESS THAN (24)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P23_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P23_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P24 VALUES LESS THAN (25)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P24_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P24_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P25 VALUES LESS THAN (26)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P25_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P25_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P26 VALUES LESS THAN (27)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P26_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P26_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P27 VALUES LESS THAN (28)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P27_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P27_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P28 VALUES LESS THAN (29)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P28_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P28_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P29 VALUES LESS THAN (30)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P29_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P29_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P30 VALUES LESS THAN (31)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P30_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P30_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL ),  
  PARTITION P31 VALUES LESS THAN (32)
    NOLOGGING
    NOCOMPRESS 
    TABLESPACE MTPKG_BILL
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ( SUBPARTITION P31_0 VALUES LESS THAN (1)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_1 VALUES LESS THAN (2)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_2 VALUES LESS THAN (3)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_3 VALUES LESS THAN (4)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_4 VALUES LESS THAN (5)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_5 VALUES LESS THAN (6)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_6 VALUES LESS THAN (7)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_7 VALUES LESS THAN (8)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_8 VALUES LESS THAN (9)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_9 VALUES LESS THAN (10)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_10 VALUES LESS THAN (11)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_11 VALUES LESS THAN (12)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_12 VALUES LESS THAN (13)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_13 VALUES LESS THAN (14)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_14 VALUES LESS THAN (15)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_15 VALUES LESS THAN (16)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_16 VALUES LESS THAN (17)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_17 VALUES LESS THAN (18)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_18 VALUES LESS THAN (19)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_19 VALUES LESS THAN (20)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_20 VALUES LESS THAN (21)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_21 VALUES LESS THAN (22)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_22 VALUES LESS THAN (23)      TABLESPACE MTPKG_BILL,
    SUBPARTITION P31_23 VALUES LESS THAN (24)      TABLESPACE MTPKG_BILL )
)
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

COMMENT ON COLUMN LIVESCREEN.MTPKG_BILL.IS_PROVISIONED IS 'Da duoc tong hop hay chua?
Tranh tong hop lap khi Job: HANDLE_CHARGING_RESULT chua kip set NEXT_CHARG_TIME moi.
=> Job: HANDLE_CHARGING_RESULT phai set lai value = 0 sau khi set NEXT_CHARG_TIME moi.';

COMMENT ON COLUMN LIVESCREEN.MTPKG_BILL.EXPIRED_TIME IS 'PhaVD: Th?i h?n s? d?ng gói. Ch? dùng cho tra c?u khi thuê bao so?n KT g?i 9220';



CREATE OR REPLACE PUBLIC SYNONYM MTPKG_BILL FOR LIVESCREEN.MTPKG_BILL;
