ALTER TABLE LIVESCREEN.MTPKG_FEE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_FEE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_FEE
(
  FEE_ID      NUMBER(7)                         NOT NULL,
  PKGD_ID     VARCHAR2(127 BYTE)                NOT NULL,
  START_TIME  DATE                              NOT NULL,
  END_TIME    DATE                              NOT NULL,
  FEE         NUMBER(9,5)                       NOT NULL,
  CHARG_TYPE  NUMBER(1)                         NOT NULL
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_FEE.CHARG_TYPE IS '1: ACTIVE; 2: RECURRENT';



CREATE UNIQUE INDEX LIVESCREEN.MT_PCK_FEE_PK ON LIVESCREEN.MTPKG_FEE
(FEE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_FEE_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_FEE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column FEE_ID
  :new.FEE_ID := MTPKG_FEE_SEQ.nextval;
END MTPKG_FEE_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_FEE FOR LIVESCREEN.MTPKG_FEE;


ALTER TABLE LIVESCREEN.MTPKG_FEE ADD (
  CONSTRAINT MT_PCK_FEE_PK
  PRIMARY KEY
  (FEE_ID)
  USING INDEX LIVESCREEN.MT_PCK_FEE_PK
  ENABLE VALIDATE);
