ALTER TABLE LIVESCREEN.MTPKG_MESSAGE_QUEUE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_MESSAGE_QUEUE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_MESSAGE_QUEUE
(
  MSISDN        VARCHAR2(15 BYTE)               NOT NULL,
  ID            NUMBER(31),
  STATUS        NUMBER(1)                       DEFAULT 0                     NOT NULL,
  RESP_TYPE     VARCHAR2(15 BYTE),
  SEND_TIME     DATE                            NOT NULL,
  SENT_TIME     DATE,
  CONTENT       VARCHAR2(3071 BYTE)             NOT NULL,
  PRIORITY      NUMBER(1),
  ERROR_CODE    NUMBER(10),
  MESSAGE_ID    VARCHAR2(100 BYTE),
  ERROR_DETAIL  VARCHAR2(255 BYTE),
  PKGD_ID       VARCHAR2(127 BYTE),
  INSERT_TIME   DATE                            DEFAULT sysdate
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.ID IS 'Khoa chinh';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.STATUS IS '0: pending (Chua xu ly hoac xu ly khong thanh cong), 1: processing (Dang xu ly), 2: done (Xu ly xong)';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.RESP_TYPE IS 'SMS, MEDIA';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.SEND_TIME IS 'Thoi gian can gui tin';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.SENT_TIME IS 'Thoi gian gui tin thanh cong';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.CONTENT IS 'Noi dung tin';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.PRIORITY IS 'Uu tien gui cac SMS thong bao toi khach hang';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.ERROR_CODE IS 'Ma loi do SMSC tra ve';

COMMENT ON COLUMN LIVESCREEN.MTPKG_MESSAGE_QUEUE.MESSAGE_ID IS 'La truong trong ban tin SMPP de map voi ban tin DeliveryReport de nhan biet tin nhan da den thue bao hay chua';



CREATE INDEX LIVESCREEN.MTPKG_MESSAGE_QUEUE_MID_IDX ON LIVESCREEN.MTPKG_MESSAGE_QUEUE
(MESSAGE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.MTPKG_MESSAGE_QUEUE_PK ON LIVESCREEN.MTPKG_MESSAGE_QUEUE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_MESSAGE_QUEUE_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_MESSAGE_QUEUE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MTPKG_MESSAGE_QUEUE_SEQ.nextval;
END MTPKG_MESSAGE_QUEUE_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_MESSAGE_QUEUE FOR LIVESCREEN.MTPKG_MESSAGE_QUEUE;


ALTER TABLE LIVESCREEN.MTPKG_MESSAGE_QUEUE ADD (
  CONSTRAINT MTPKG_MESSAGE_QUEUE_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.MTPKG_MESSAGE_QUEUE_PK
  ENABLE VALIDATE);
