ALTER TABLE LIVESCREEN.MTPKG_PACKAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_PACKAGE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_PACKAGE
(
  PKG_ID           NUMBER(7),
  PKG_NAME         VARCHAR2(255 BYTE),
  STATUS           NUMBER(1),
  GROUP_ID         NUMBER(7),
  MAX_SMS_PER_PKG  NUMBER(2)                    DEFAULT 4,
  CP_ID            NUMBER(30)
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_PACKAGE.STATUS IS '1: ON, 0: OFF';



CREATE UNIQUE INDEX LIVESCREEN.MTPKG_PACKAGE_PK ON LIVESCREEN.MTPKG_PACKAGE
(PKG_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_PACKAGE_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_PACKAGE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PKG_ID
  :new.PKG_ID := MTPKG_PACKAGE_SEQ.nextval;
END MTPKG_PACKAGE_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_PACKAGE FOR LIVESCREEN.MTPKG_PACKAGE;


ALTER TABLE LIVESCREEN.MTPKG_PACKAGE ADD (
  CONSTRAINT MTPKG_PACKAGE_PK
  PRIMARY KEY
  (PKG_ID)
  USING INDEX LIVESCREEN.MTPKG_PACKAGE_PK
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.MTPKG_PACKAGE ADD (
  CONSTRAINT MTPKG_PACKAGE_R01 
  FOREIGN KEY (GROUP_ID) 
  REFERENCES LIVESCREEN.MTPKG_GROUP (GROUP_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
