ALTER TABLE LIVESCREEN.MTPKG_DISCOUNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_DISCOUNT CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_DISCOUNT
(
  DISCOUNT_ID    NUMBER(7)                      NOT NULL,
  START_TIME     DATE                           NOT NULL,
  END_TIME       DATE                           NOT NULL,
  DISCOUNT       NUMBER(9,5),
  MSISDNS        VARCHAR2(15 BYTE),
  CHARG_TYPE     NUMBER(1)                      NOT NULL,
  PKGD_ID        VARCHAR2(127 BYTE)             NOT NULL,
  RATE_DISCOUNT  NUMBER(5,2)
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_DISCOUNT.CHARG_TYPE IS '1: ACTIVE; 2: RECURRENT';



CREATE UNIQUE INDEX LIVESCREEN.MTPKG_DISCOUNT_PK ON LIVESCREEN.MTPKG_DISCOUNT
(DISCOUNT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_DISCOUNT_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_DISCOUNT
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DISCOUNT_ID
  :new.DISCOUNT_ID := MTPKG_DISCOUNT_SEQ.nextval;
END MTPKG_DISCOUNT_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_DISCOUNT FOR LIVESCREEN.MTPKG_DISCOUNT;


ALTER TABLE LIVESCREEN.MTPKG_DISCOUNT ADD (
  CONSTRAINT MTPKG_DISCOUNT_PK
  PRIMARY KEY
  (DISCOUNT_ID)
  USING INDEX LIVESCREEN.MTPKG_DISCOUNT_PK
  ENABLE VALIDATE);
