ALTER TABLE LIVESCREEN.MTPKG_RECOVER_REQ
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_RECOVER_REQ CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_RECOVER_REQ
(
  MSISDN    VARCHAR2(15 CHAR)                   NOT NULL,
  REQ_TIME  DATE                                NOT NULL,
  STATUS    NUMBER(2)                           DEFAULT 0                     NOT NULL,
  REQ_ID    NUMBER(15)                          NOT NULL,
  PKGD_ID   VARCHAR2(127 BYTE)                  NOT NULL
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_RECOVER_REQ.STATUS IS '0: Yêu c?u KP m?i, Job RECOVER_PROCESS chua ti?p nh?n x? lý yêu c?u
1: Job MT_RECOVER_PROCESS ti?p nh?n x? lý yêu c?u';



CREATE UNIQUE INDEX LIVESCREEN.IDX_MT_RECOVER_REQ_PK ON LIVESCREEN.MTPKG_RECOVER_REQ
(REQ_ID)
LOGGING
TABLESPACE MTPKG_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_RECOVER_REQ_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_RECOVER_REQ
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column REQ_ID
  :new.REQ_ID := MTPKG_RECOVER_REQ_SEQ.nextval;
END MTPKG_RECOVER_REQ_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_RECOVER_REQ FOR LIVESCREEN.MTPKG_RECOVER_REQ;


ALTER TABLE LIVESCREEN.MTPKG_RECOVER_REQ ADD (
  CONSTRAINT IDX_MT_RECOVER_REQ_PK
  PRIMARY KEY
  (REQ_ID)
  USING INDEX LIVESCREEN.IDX_MT_RECOVER_REQ_PK
  ENABLE VALIDATE);
