DROP TABLE LIVESCREEN.MTPKG_TMP_MSISDN CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_TMP_MSISDN
(
  MSISDN  VARCHAR2(15 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_TMP_MSISDN FOR LIVESCREEN.MTPKG_TMP_MSISDN;
