ALTER TABLE LIVESCREEN.MTPKG_DOWNLOAD
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.MTPKG_DOWNLOAD CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.MTPKG_DOWNLOAD
(
  DOWNLOAD_ID           NUMBER(31)              NOT NULL,
  CP_ID                 NUMBER(30)              NOT NULL,
  PKG_ID                NUMBER(7),
  URL                   VARCHAR2(500 CHAR)      NOT NULL,
  DATE_PLUG             DATE,
  TIME                  VARCHAR2(20 CHAR),
  AMOUNTS               NUMBER(20),
  REPEATS               NUMBER(10),
  ISTIME                NUMBER(5),
  STATUS                NUMBER(10)              NOT NULL,
  CREATEDBY             NUMBER(30),
  CREATEDDATE           DATE,
  IS_APPROVE            NUMBER(5)               DEFAULT 1,
  TYPE                  NUMBER(5)               DEFAULT 0,
  UPDATETIME            DATE,
  LAST_CONTENTS         VARCHAR2(3999 CHAR),
  LAST_CONTENTS_CRC32   NUMBER(31),
  LAST_DOWNLOAD_RESULT  VARCHAR2(3999 CHAR),
  LAST_DOWNLOAD_TIME    DATE,
  SUB_TOPIC_NAME        VARCHAR2(127 BYTE)      DEFAULT 'Default',
  RESP_TYPE             VARCHAR2(15 BYTE),
  TIME_TYPE             NUMBER                  DEFAULT 0,
  TIME_SELECT           VARCHAR2(1000 BYTE)
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.MTPKG_DOWNLOAD.STATUS IS '0: Ready; 1: Not Ready';

COMMENT ON COLUMN LIVESCREEN.MTPKG_DOWNLOAD.IS_APPROVE IS '0: Not Approved; 1: Approved';

COMMENT ON COLUMN LIVESCREEN.MTPKG_DOWNLOAD.TYPE IS 'Chua su dung';

COMMENT ON COLUMN LIVESCREEN.MTPKG_DOWNLOAD.RESP_TYPE IS 'SMS; MEDIA';

COMMENT ON COLUMN LIVESCREEN.MTPKG_DOWNLOAD.TIME_TYPE IS '0: Date; 1: Week; 2: Month';

COMMENT ON COLUMN LIVESCREEN.MTPKG_DOWNLOAD.TIME_SELECT IS 'Thoi gian chon tuan, thang, cach nhau boi dau , viet lien khong co dau cach 1. Tuan = MON, TUE, WED, THU, FRI, SAT, SUN hoac SUN-SAT 2. Thang = 1-31 hoac 1,2,3';



CREATE UNIQUE INDEX LIVESCREEN.MTPKG_DOWNLOAD_PK ON LIVESCREEN.MTPKG_DOWNLOAD
(DOWNLOAD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_DOWNLOAD_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_DOWNLOAD
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DOWNLOAD_ID
  :new.DOWNLOAD_ID := MTPKG_DOWNLOAD_SEQ.nextval;
END MTPKG_DOWNLOAD_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM MTPKG_DOWNLOAD FOR LIVESCREEN.MTPKG_DOWNLOAD;


ALTER TABLE LIVESCREEN.MTPKG_DOWNLOAD ADD (
  CONSTRAINT MTPKG_DOWNLOAD_PK
  PRIMARY KEY
  (DOWNLOAD_ID)
  USING INDEX LIVESCREEN.MTPKG_DOWNLOAD_PK
  ENABLE VALIDATE);
