ALTER TABLE LIVESCREEN.OMAP_EVENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.OMAP_EVENT CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.OMAP_EVENT
(
  ID            NUMBER(15)                      NOT NULL,
  NAME          NVARCHAR2(100),
  EVENT_TIME    DATE,
  EVENT_DETAIL  NVARCHAR2(2000),
  USER_ID       NUMBER,
  USERNAME      NVARCHAR2(100),
  IP            NVARCHAR2(20),
  URL           NVARCHAR2(100)
)
NOCOMPRESS 
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING
PARTITION BY RANGE (EVENT_TIME)
(  
  PARTITION PARTITION1 VALUES LESS THAN (TO_DATE(' 2010-02-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    LOGGING
    NOCOMPRESS 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   1
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
)
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.OMAP_EVENT_PK ON LIVESCREEN.OMAP_EVENT
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.OMAP_EVENT_TRG 
BEFORE INSERT ON LIVESCREEN.OMAP_EVENT
FOR EACH ROW
DISABLE
BEGIN
  SELECT OMAP_EVENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM OMAP_EVENT FOR LIVESCREEN.OMAP_EVENT;


ALTER TABLE LIVESCREEN.OMAP_EVENT ADD (
  CONSTRAINT OMAP_EVENT_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.OMAP_EVENT_PK
  ENABLE VALIDATE);
