ALTER TABLE LIVESCREEN.PLSQL_PROFILER_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.PLSQL_PROFILER_DATA CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.PLSQL_PROFILER_DATA
(
  RUNID        NUMBER,
  UNIT_NUMBER  NUMBER,
  LINE#        NUMBER                           NOT NULL,
  TOTAL_OCCUR  NUMBER,
  TOTAL_TIME   NUMBER,
  MIN_TIME     NUMBER,
  MAX_TIME     NUMBER,
  SPARE1       NUMBER,
  SPARE2       NUMBER,
  SPARE3       NUMBER,
  SPARE4       NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LIVESCREEN.PLSQL_PROFILER_DATA IS 'Accumulated data from all profiler runs';



CREATE UNIQUE INDEX LIVESCREEN.PK_PLSQL_PROFILER_DATA ON LIVESCREEN.PLSQL_PROFILER_DATA
(RUNID, UNIT_NUMBER, LINE#)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX LIVESCREEN.PLSQL_PROFILER_DINDEX ON LIVESCREEN.PLSQL_PROFILER_DATA
(RUNID, UNIT_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM PLSQL_PROFILER_DATA FOR LIVESCREEN.PLSQL_PROFILER_DATA;


ALTER TABLE LIVESCREEN.PLSQL_PROFILER_DATA ADD (
  PRIMARY KEY
  (RUNID, UNIT_NUMBER, LINE#)
  USING INDEX LIVESCREEN.PK_PLSQL_PROFILER_DATA
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.PLSQL_PROFILER_DATA ADD (
  FOREIGN KEY (RUNID, UNIT_NUMBER) 
  REFERENCES LIVESCREEN.PLSQL_PROFILER_UNITS (RUNID,UNIT_NUMBER)
  ENABLE VALIDATE);
