ALTER TABLE LIVESCREEN.PLSQL_PROFILER_UNITS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.PLSQL_PROFILER_UNITS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.PLSQL_PROFILER_UNITS
(
  RUNID           NUMBER,
  UNIT_NUMBER     NUMBER,
  UNIT_TYPE       VARCHAR2(32 BYTE),
  UNIT_OWNER      VARCHAR2(32 BYTE),
  UNIT_NAME       VARCHAR2(32 BYTE),
  UNIT_TIMESTAMP  DATE,
  TOTAL_TIME      NUMBER                        DEFAULT 0,
  SPARE1          NUMBER,
  SPARE2          NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LIVESCREEN.PLSQL_PROFILER_UNITS IS 'Information about each library unit in a run';



CREATE UNIQUE INDEX LIVESCREEN.PK_PLSQL_PROFILER_UNITS ON LIVESCREEN.PLSQL_PROFILER_UNITS
(RUNID, UNIT_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM PLSQL_PROFILER_UNITS FOR LIVESCREEN.PLSQL_PROFILER_UNITS;


ALTER TABLE LIVESCREEN.PLSQL_PROFILER_UNITS ADD (
  CHECK ("TOTAL_TIME" IS NOT NULL)
  ENABLE VALIDATE,
  PRIMARY KEY
  (RUNID, UNIT_NUMBER)
  USING INDEX LIVESCREEN.PK_PLSQL_PROFILER_UNITS
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.PLSQL_PROFILER_UNITS ADD (
  FOREIGN KEY (RUNID) 
  REFERENCES LIVESCREEN.PLSQL_PROFILER_RUNS (RUNID)
  ENABLE VALIDATE);
