DROP TABLE LIVESCREEN.PROFILE_TOPIC CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.PROFILE_TOPIC
(
  MSISDN    VARCHAR2(15 BYTE)                   NOT NULL,
  TOPIC_ID  NUMBER                              NOT NULL
)
TABLESPACE PRO_TOPIC
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX LIVESCREEN.PROFILE_TOPIC_INDX ON LIVESCREEN.PROFILE_TOPIC
(MSISDN)
LOGGING
TABLESPACE PRO_TOPIC_INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM PROFILE_TOPIC FOR LIVESCREEN.PROFILE_TOPIC;
