DROP TABLE LIVESCREEN.PROFILE_TMP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.PROFILE_TMP
(
  MSISDN  VARCHAR2(20 BYTE)                     NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM PROFILE_TMP FOR LIVESCREEN.PROFILE_TMP;
