ALTER TABLE LIVESCREEN.PROFILE_TOPIC_HIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.PROFILE_TOPIC_HIST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.PROFILE_TOPIC_HIST
(
  ID          NUMBER                            NOT NULL,
  MSISDN      VARCHAR2(15 BYTE),
  TOPIC_ID    NUMBER,
  CHANGETIME  DATE,
  ACTIONS     VARCHAR2(100 BYTE),
  SOURCE      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.PROFILE_TOPIC_HIST.ACTIONS IS '    UNKNOWN(0),     ON_TOPIC(1),     ON_ALL_TOPIC(2),     OFF_TOPIC(3),     OFF_ALL_TOPIC(4),     CHANGE_COS(5);';



--  There is no statement for index LIVESCREEN.SYS_C0012669.
--  The object is created when the parent object is created.

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_TOPIC_HIST FOR LIVESCREEN.PROFILE_TOPIC_HIST;


ALTER TABLE LIVESCREEN.PROFILE_TOPIC_HIST ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);
