DROP TABLE LIVESCREEN.PROGRAMS_HIST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.PROGRAMS_HIST
(
  ID            NUMBER(30)                      NOT NULL,
  PROGRAM_ID    VARCHAR2(30 BYTE)               NOT NULL,
  TIMEPLUG      VARCHAR2(100 BYTE),
  SUBCONTENTS   VARCHAR2(200 BYTE),
  CPS_TOPIC_ID  NUMBER(30)                      NOT NULL,
  STATUS        NUMBER(5)                       DEFAULT 0,
  CREATEDDATE   DATE,
  USER_ID       NUMBER                          NOT NULL,
  ACTIONS       VARCHAR2(300 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM PROGRAMS_HIST FOR LIVESCREEN.PROGRAMS_HIST;
