DROP TABLE LIVESCREEN.RPT_ACTION_LOG CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.RPT_ACTION_LOG
(
  LOG_USER_NAME    VARCHAR2(255 BYTE)           NOT NULL,
  LOG_ACTION       VARCHAR2(511 BYTE),
  LOG_DESCRIPTION  VARCHAR2(3071 BYTE),
  LOG_TIME         DATE,
  LOG_LEVEL        NUMBER(1),
  LOG_ID           NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM RPT_ACTION_LOG FOR LIVESCREEN.RPT_ACTION_LOG;
