DROP TABLE LIVESCREEN.RTBS_HIS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.RTBS_HIS
(
  BALANCE    NUMBER,
  RESULT     VARCHAR2(20 BYTE),
  MSISDN     VARCHAR2(20 BYTE),
  DATA_PART  NUMBER(6)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM RTBS_HIS FOR LIVESCREEN.RTBS_HIS;
