ALTER TABLE LIVESCREEN.SCHEDULE_REBUILD_COMMAND
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SCHEDULE_REBUILD_COMMAND CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SCHEDULE_REBUILD_COMMAND
(
  COMMAND_ID           NUMBER(5)                NOT NULL,
  EXECUTE_TIME         DATE,
  IMMEDIATELY          NUMBER(5),
  DESCRIPTION          VARCHAR2(2000 CHAR),
  LAST_EXECUTE_STATUS  NUMBER(5),
  LAST_EXECUTE_RESULT  VARCHAR2(2000 CHAR),
  LAST_FINISH_TIME     DATE,
  STATUS               NUMBER(5)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.SCHEDULE_REBUILD_COMMAND.IMMEDIATELY IS '1: chay ngay, khong can quan tam den thoi gian. 0: chay theo truong EXECUTE_TIME';

COMMENT ON COLUMN LIVESCREEN.SCHEDULE_REBUILD_COMMAND.STATUS IS '0: chua xu ly; 1: da xu ly xong; 2: dang xu ly; 3: loi khac';



CREATE UNIQUE INDEX LIVESCREEN.SCHEDULE_REBUILD_COMMAND_PK ON LIVESCREEN.SCHEDULE_REBUILD_COMMAND
(COMMAND_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.SCHEDULE_REBUILD_COMMAND_TRG  
   before insert on "LIVESCREEN"."SCHEDULE_REBUILD_COMMAND" 
   for each row
begin  
   if inserting then 
      if :NEW."COMMAND_ID" is null then 
         select SCHEDULE_REBUILD_SEQ.nextval into :NEW."COMMAND_ID" from dual; 
      end if; 
   end if; 
end;
/


ALTER TABLE LIVESCREEN.SCHEDULE_REBUILD_COMMAND ADD (
  CONSTRAINT SCHEDULE_REBUILD_COMMAND_PK
  PRIMARY KEY
  (COMMAND_ID)
  USING INDEX LIVESCREEN.SCHEDULE_REBUILD_COMMAND_PK
  ENABLE VALIDATE);
