ALTER TABLE LIVESCREEN.SCHEDULE_ZONE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SCHEDULE_ZONE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SCHEDULE_ZONE_DETAIL
(
  SCHEDULE_ID   NUMBER(15)                      NOT NULL,
  ZONE_ID       NUMBER(15)                      NOT NULL,
  NUM_OF_SLOTS  NUMBER(5)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.CATEGORY_ZONE_DETAIL_PK ON LIVESCREEN.SCHEDULE_ZONE_DETAIL
(SCHEDULE_ID, ZONE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SCHEDULE_ZONE_DETAIL FOR LIVESCREEN.SCHEDULE_ZONE_DETAIL;


ALTER TABLE LIVESCREEN.SCHEDULE_ZONE_DETAIL ADD (
  CONSTRAINT CATEGORY_ZONE_DETAIL_PK
  PRIMARY KEY
  (SCHEDULE_ID, ZONE_ID)
  USING INDEX LIVESCREEN.CATEGORY_ZONE_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.SCHEDULE_ZONE_DETAIL ADD (
  CONSTRAINT SCHEDULE_ZONE_DETAIL_CATE_FK1 
  FOREIGN KEY (SCHEDULE_ID) 
  REFERENCES LIVESCREEN.CATEGORY_SCHEDULE (SCHEDULE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE,
  CONSTRAINT SCHEDULE_ZONE_DETAIL_ZONE_FK1 
  FOREIGN KEY (ZONE_ID) 
  REFERENCES LIVESCREEN.ZONE (ZONE_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
