DROP TABLE LIVESCREEN.SHORTCODE_MONEY CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SHORTCODE_MONEY
(
  SHORT_CODE  VARCHAR2(50 BYTE),
  MONEY       VARCHAR2(50 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM SHORTCODE_MONEY FOR LIVESCREEN.SHORTCODE_MONEY;
