DROP TABLE LIVESCREEN.SMS_BROADCAST_DEST CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SMS_BROADCAST_DEST
(
  MSISDN            VARCHAR2(20 BYTE)           NOT NULL,
  STATUS            NUMBER                      NOT NULL,
  BROADCAST_ID      NUMBER                      NOT NULL,
  INSERT_TIME       TIMESTAMP(6)                DEFAULT sysdate,
  SENT_TIME         TIMESTAMP(6),
  SENT_RESULT       NUMBER(10),
  SENT_RESULT_DESC  VARCHAR2(100 BYTE),
  ID                NUMBER(10)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.SMS_BROADCAST_DEST.STATUS IS '0 SEND, 1 processing, 2 sented';



CREATE OR REPLACE PUBLIC SYNONYM SMS_BROADCAST_DEST FOR LIVESCREEN.SMS_BROADCAST_DEST;
