ALTER TABLE LIVESCREEN.SMSCB_CENTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SMSCB_CENTER CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SMSCB_CENTER
(
  SMSCB_CENTER_ID             VARCHAR2(20 CHAR) NOT NULL,
  SMSCB_CENTER_NAME           VARCHAR2(20 CHAR),
  SMSCB_URI                   VARCHAR2(500 CHAR),
  TOTAL_BSC                   NUMBER(5),
  TOTAL_RNC                   NUMBER(5),
  TOTAL_2G_CELL               NUMBER(9),
  TOTAL_3G_CELL               NUMBER(9),
  ENABLE_UPDATER              VARCHAR2(20 CHAR) DEFAULT 'TRUE',
  SCHEDULED_UPDATER_TIME      VARCHAR2(20 CHAR) DEFAULT '03:00',
  CONNECTION_TIMEOUT          NUMBER(9),
  SO_TIMEOUT                  NUMBER(9),
  GLOBAL_MAX_RETRY_NUM        NUMBER(5),
  GLOBAL_RETRY_INTEVAL_MS     NUMBER(9),
  BC_QUERY_MAX_RETRY_NUM      NUMBER(5),
  BC_QUERY_RETRY_INTERVAL_MS  NUMBER(9)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.SMSCB_CENTER.ENABLE_UPDATER IS 'TRUE or FALSE';

COMMENT ON COLUMN LIVESCREEN.SMSCB_CENTER.SCHEDULED_UPDATER_TIME IS 'eg: 03:00';



CREATE UNIQUE INDEX LIVESCREEN.SMSCB_CENTER_PK ON LIVESCREEN.SMSCB_CENTER
(SMSCB_CENTER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SMSCB_CENTER FOR LIVESCREEN.SMSCB_CENTER;


ALTER TABLE LIVESCREEN.SMSCB_CENTER ADD (
  CONSTRAINT SMSCB_CENTER_PK
  PRIMARY KEY
  (SMSCB_CENTER_ID)
  USING INDEX LIVESCREEN.SMSCB_CENTER_PK
  ENABLE VALIDATE);
