ALTER TABLE LIVESCREEN.SQLN_PROF_RUNS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SQLN_PROF_RUNS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SQLN_PROF_RUNS
(
  PROJ_ID  NUMBER                               NOT NULL,
  RUNID    NUMBER                               NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.PK_SQLN_PROF_RUNS ON LIVESCREEN.SQLN_PROF_RUNS
(PROJ_ID, RUNID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SQLN_PROF_RUNS FOR LIVESCREEN.SQLN_PROF_RUNS;


ALTER TABLE LIVESCREEN.SQLN_PROF_RUNS ADD (
  CONSTRAINT PK_SQLN_PROF_RUNS
  PRIMARY KEY
  (PROJ_ID, RUNID)
  USING INDEX LIVESCREEN.PK_SQLN_PROF_RUNS
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.SQLN_PROF_RUNS ADD (
  CONSTRAINT FK_PROJ_RUNID 
  FOREIGN KEY (RUNID) 
  REFERENCES LIVESCREEN.PLSQL_PROFILER_RUNS (RUNID)
  ENABLE VALIDATE,
  CONSTRAINT FK_PROJ_RUNS_PROJ_ID 
  FOREIGN KEY (PROJ_ID) 
  REFERENCES LIVESCREEN.SQLN_PROF_PROFILES (PROJ_ID)
  ENABLE VALIDATE);
