ALTER TABLE LIVESCREEN.SQLN_PROF_UNITS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SQLN_PROF_UNITS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SQLN_PROF_UNITS
(
  PROJ_ID    NUMBER                             NOT NULL,
  UNIT_NAME  VARCHAR2(30 BYTE)                  NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.PK_SQLN_PROF_UNITS ON LIVESCREEN.SQLN_PROF_UNITS
(PROJ_ID, UNIT_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SQLN_PROF_UNITS FOR LIVESCREEN.SQLN_PROF_UNITS;


ALTER TABLE LIVESCREEN.SQLN_PROF_UNITS ADD (
  CONSTRAINT PK_SQLN_PROF_UNITS
  PRIMARY KEY
  (PROJ_ID, UNIT_NAME)
  USING INDEX LIVESCREEN.PK_SQLN_PROF_UNITS
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.SQLN_PROF_UNITS ADD (
  CONSTRAINT FK_PROJ_ID 
  FOREIGN KEY (PROJ_ID) 
  REFERENCES LIVESCREEN.SQLN_PROF_PROFILES (PROJ_ID)
  ENABLE VALIDATE);
