ALTER TABLE LIVESCREEN.SQLN_PROF_PROFILES
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SQLN_PROF_PROFILES CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SQLN_PROF_PROFILES
(
  PROJ_ID       NUMBER                          NOT NULL,
  PROJ_NAME     VARCHAR2(2047 BYTE),
  PROJ_COMMENT  VARCHAR2(2047 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.PK_PROJ_ID ON LIVESCREEN.SQLN_PROF_PROFILES
(PROJ_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SQLN_PROF_PROFILES FOR LIVESCREEN.SQLN_PROF_PROFILES;


ALTER TABLE LIVESCREEN.SQLN_PROF_PROFILES ADD (
  CONSTRAINT PK_PROJ_ID
  PRIMARY KEY
  (PROJ_ID)
  USING INDEX LIVESCREEN.PK_PROJ_ID
  ENABLE VALIDATE);
