ALTER TABLE LIVESCREEN.SQLN_PROF_ANB
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SQLN_PROF_ANB CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SQLN_PROF_ANB
(
  RUNID        NUMBER                           NOT NULL,
  UNIT_NUMBER  NUMBER                           NOT NULL,
  LINE#        NUMBER                           NOT NULL,
  TEXT         VARCHAR2(2048 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LIVESCREEN.SQLN_PROF_ANB IS 'Annonymous block source';

COMMENT ON COLUMN LIVESCREEN.SQLN_PROF_ANB.RUNID IS 'PLSQL_PROFILER_RUNS';

COMMENT ON COLUMN LIVESCREEN.SQLN_PROF_ANB.UNIT_NUMBER IS 'PLSQL_PROFILER_UNITS';



CREATE UNIQUE INDEX LIVESCREEN.PK_SQLN_PROF_ANB ON LIVESCREEN.SQLN_PROF_ANB
(RUNID, UNIT_NUMBER, LINE#)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SQLN_PROF_ANB FOR LIVESCREEN.SQLN_PROF_ANB;


ALTER TABLE LIVESCREEN.SQLN_PROF_ANB ADD (
  CONSTRAINT PK_SQLN_PROF_ANB
  PRIMARY KEY
  (RUNID, UNIT_NUMBER, LINE#)
  USING INDEX LIVESCREEN.PK_SQLN_PROF_ANB
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.SQLN_PROF_ANB ADD (
  CONSTRAINT FK_SQLN_ANB 
  FOREIGN KEY (RUNID, UNIT_NUMBER) 
  REFERENCES LIVESCREEN.PLSQL_PROFILER_UNITS (RUNID,UNIT_NUMBER)
  ENABLE VALIDATE);
