ALTER TABLE LIVESCREEN.SQLN_PROF_UNIT_HASH
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SQLN_PROF_UNIT_HASH CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SQLN_PROF_UNIT_HASH
(
  RUNID        NUMBER                           NOT NULL,
  UNIT_NUMBER  NUMBER                           NOT NULL,
  HASH         VARCHAR2(32 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LIVESCREEN.SQLN_PROF_UNIT_HASH IS 'Hash of unit source code (1:1 with PLSQL_PROFILER_UNITS)';



CREATE UNIQUE INDEX LIVESCREEN.PK_SQLN_PROF_HASH ON LIVESCREEN.SQLN_PROF_UNIT_HASH
(RUNID, UNIT_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SQLN_PROF_UNIT_HASH FOR LIVESCREEN.SQLN_PROF_UNIT_HASH;


ALTER TABLE LIVESCREEN.SQLN_PROF_UNIT_HASH ADD (
  CONSTRAINT PK_SQLN_PROF_HASH
  PRIMARY KEY
  (RUNID, UNIT_NUMBER)
  USING INDEX LIVESCREEN.PK_SQLN_PROF_HASH
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.SQLN_PROF_UNIT_HASH ADD (
  CONSTRAINT FK_SQLN_UNIT_HASH 
  FOREIGN KEY (RUNID, UNIT_NUMBER) 
  REFERENCES LIVESCREEN.PLSQL_PROFILER_UNITS (RUNID,UNIT_NUMBER)
  ENABLE VALIDATE);
