ALTER TABLE LIVESCREEN.SQLN_PROF_SESS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.SQLN_PROF_SESS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SQLN_PROF_SESS
(
  RUNID    NUMBER                               NOT NULL,
  STAT_ID  NUMBER                               NOT NULL,
  VALUE    NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LIVESCREEN.SQLN_PROF_SESS IS 'Session Statistics Info For a Run';

COMMENT ON COLUMN LIVESCREEN.SQLN_PROF_SESS.RUNID IS 'PLSQL_PROFILER_RUNS';

COMMENT ON COLUMN LIVESCREEN.SQLN_PROF_SESS.STAT_ID IS 'STATISTIC# from V$STATNAME';

COMMENT ON COLUMN LIVESCREEN.SQLN_PROF_SESS.VALUE IS 'VALUE from V$SESSTAT for a session SID and STATISTIC#';



CREATE UNIQUE INDEX LIVESCREEN.PK_SQLN_PROF_SESS ON LIVESCREEN.SQLN_PROF_SESS
(RUNID, STAT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM SQLN_PROF_SESS FOR LIVESCREEN.SQLN_PROF_SESS;


ALTER TABLE LIVESCREEN.SQLN_PROF_SESS ADD (
  CONSTRAINT PK_SQLN_PROF_SESS
  PRIMARY KEY
  (RUNID, STAT_ID)
  USING INDEX LIVESCREEN.PK_SQLN_PROF_SESS
  ENABLE VALIDATE);

ALTER TABLE LIVESCREEN.SQLN_PROF_SESS ADD (
  FOREIGN KEY (RUNID) 
  REFERENCES LIVESCREEN.PLSQL_PROFILER_RUNS (RUNID)
  ENABLE VALIDATE);
