ALTER TABLE LIVESCREEN.STATIONS
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.STATIONS CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.STATIONS
(
  STATIONS_ID   NUMBER(20)                      NOT NULL,
  ZONES_ID      NUMBER(20)                      NOT NULL,
  STATIONSNAME  VARCHAR2(50 BYTE)               NOT NULL,
  DESCRIPTIONS  VARCHAR2(200 BYTE)              DEFAULT 'Nothing',
  CREATEDDATE   DATE,
  USER_ID       NUMBER,
  STATUS        NUMBER(5)                       DEFAULT 1
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.STATIONS_NAME_UK ON LIVESCREEN.STATIONS
(ZONES_ID, STATIONSNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.STATION_ID ON LIVESCREEN.STATIONS
(STATIONS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE SYNONYM CBC.STATIONS FOR LIVESCREEN.STATIONS;


CREATE OR REPLACE PUBLIC SYNONYM STATIONS FOR LIVESCREEN.STATIONS;


ALTER TABLE LIVESCREEN.STATIONS ADD (
  CONSTRAINT STATION_ID
  PRIMARY KEY
  (STATIONS_ID)
  USING INDEX LIVESCREEN.STATION_ID
  ENABLE VALIDATE,
  CONSTRAINT STATIONS_NAME_UK
  UNIQUE (ZONES_ID, STATIONSNAME)
  USING INDEX LIVESCREEN.STATIONS_NAME_UK
  ENABLE VALIDATE);
