DROP TABLE LIVESCREEN.SYSTEM_RESOURCES CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.SYSTEM_RESOURCES
(
  ID            NUMBER(30),
  IP            VARCHAR2(16 BYTE),
  SAMPLED_TIME  DATE,
  TYPE          VARCHAR2(15 BYTE),
  DESCRIPTION   VARCHAR2(200 BYTE),
  USED          NUMBER(10)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.SYSTEM_RESOURCES.TYPE IS '1: cpu; 2:ram; 3: harddisk';



CREATE OR REPLACE PUBLIC SYNONYM SYSTEM_RESOURCES FOR LIVESCREEN.SYSTEM_RESOURCES;
