DROP TABLE LIVESCREEN.TOPIC_CONFIG_MENU CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.TOPIC_CONFIG_MENU
(
  ID        NUMBER                              NOT NULL,
  TOPIC_ID  NUMBER                              NOT NULL,
  MENU_ID   VARCHAR2(100 BYTE)                  NOT NULL,
  STATUS    NUMBER                              NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM TOPIC_CONFIG_MENU FOR LIVESCREEN.TOPIC_CONFIG_MENU;
