ALTER TABLE LIVESCREEN.TOPIC_SCHEDULE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.TOPIC_SCHEDULE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.TOPIC_SCHEDULE
(
  ID                           VARCHAR2(100 CHAR),
  TIME                         VARCHAR2(10 CHAR),
  TOPIC_ID                     NUMBER(30),
  TOPIC_NAME                   VARCHAR2(100 CHAR),
  TOPIC_RANDOM_CONFIG_ID       VARCHAR2(100 CHAR),
  LAST_UPDATED_TIME            TIMESTAMP(6),
  PROGRAM_STATUS               VARCHAR2(20 CHAR) DEFAULT 'No program',
  PROGRAM_STATUS_UPDATED_TIME  TIMESTAMP(6),
  ZONE_ID                      NUMBER(15),
  ZONE_NAME                    VARCHAR2(255 BYTE)
)
TABLESPACE TBS_KPI
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.TOPIC_SCHEDULE.PROGRAM_STATUS IS 'possible values:
"No program", "Getting program", "program filled"';



CREATE INDEX LIVESCREEN.TOPIC_SCHEDULE_INDEX1 ON LIVESCREEN.TOPIC_SCHEDULE
(TOPIC_RANDOM_CONFIG_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.TOPIC_SCHEDULE_PK ON LIVESCREEN.TOPIC_SCHEDULE
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM TOPIC_SCHEDULE FOR LIVESCREEN.TOPIC_SCHEDULE;


ALTER TABLE LIVESCREEN.TOPIC_SCHEDULE ADD (
  CONSTRAINT TOPIC_SCHEDULE_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.TOPIC_SCHEDULE_PK
  ENABLE VALIDATE);
