ALTER TABLE LIVESCREEN.TOPIC_RANDOM_CONFIG
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.TOPIC_RANDOM_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.TOPIC_RANDOM_CONFIG
(
  ID                  VARCHAR2(100 CHAR),
  START_TIME          TIMESTAMP(6),
  END_TIME            TIMESTAMP(6),
  NUMBER_OF_PROGRAMS  NUMBER(8),
  REPETITION_RATE     NUMBER(8),
  TOPIC_ID            NUMBER(30),
  TOPIC_NAME          VARCHAR2(50 CHAR),
  ZONE_ID             NUMBER(15),
  ZONE_NAME           VARCHAR2(255 BYTE),
  LAST_UPDATED_TIME   TIMESTAMP(6)
)
TABLESPACE TBS_KPI
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.TOPIC_RANDOM_CONFIG_PK ON LIVESCREEN.TOPIC_RANDOM_CONFIG
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM TOPIC_RANDOM_CONFIG FOR LIVESCREEN.TOPIC_RANDOM_CONFIG;


ALTER TABLE LIVESCREEN.TOPIC_RANDOM_CONFIG ADD (
  CONSTRAINT TOPIC_RANDOM_CONFIG_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.TOPIC_RANDOM_CONFIG_PK
  ENABLE VALIDATE);
