DROP TABLE LIVESCREEN.TOTAL_MSISDN_MONTHLY CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.TOTAL_MSISDN_MONTHLY
(
  TIME   VARCHAR2(9 BYTE),
  TOTAL  NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM TOTAL_MSISDN_MONTHLY FOR LIVESCREEN.TOTAL_MSISDN_MONTHLY;
