DROP TABLE LIVESCREEN.TRANS_LOG CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.TRANS_LOG
(
  MODULE       VARCHAR2(31 BYTE),
  MSISDN       VARCHAR2(15 BYTE),
  SEQID        VARCHAR2(15 BYTE),
  INSERT_TIME  VARCHAR2(23 BYTE),
  CONTENT      VARCHAR2(3071 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
