DROP TABLE LIVESCREEN.VAS_CDR_MT CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.VAS_CDR_MT
(
  MSISDN         VARCHAR2(21 BYTE),
  SHORT_CODE     VARCHAR2(21 BYTE),
  MT_CONTENT     VARCHAR2(512 BYTE),
  TIME           DATE,
  VAS_CDR_ID     NUMBER(31)                     NOT NULL,
  SEQ_ID         NUMBER(15),
  STATUS         NUMBER(5),
  STATUS_DETAIL  VARCHAR2(128 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
