ALTER TABLE LIVESCREEN.VAS_CDR
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.VAS_CDR CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.VAS_CDR
(
  MSISDN         VARCHAR2(21 BYTE),
  SHORT_CODE     VARCHAR2(21 BYTE),
  MO_CONTENT     VARCHAR2(512 BYTE),
  TIME           DATE,
  VAS_CDR_ID     NUMBER(31)                     NOT NULL,
  SEQ_ID         NUMBER(15),
  STATUS         NUMBER(5),
  STATUS_DETAIL  VARCHAR2(128 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.VAS_CDR_PK ON LIVESCREEN.VAS_CDR
(VAS_CDR_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.VAS_CDR_TRG 
BEFORE INSERT
ON LIVESCREEN.VAS_CDR
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column VAS_CDR_ID
  :new.VAS_CDR_ID := VAS_CDR_SEQ.nextval;
END VAS_CDR_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM VAS_CDR FOR LIVESCREEN.VAS_CDR;


ALTER TABLE LIVESCREEN.VAS_CDR ADD (
  CONSTRAINT VAS_CDR_PK
  PRIMARY KEY
  (VAS_CDR_ID)
  USING INDEX LIVESCREEN.VAS_CDR_PK
  ENABLE VALIDATE);
