ALTER TABLE LIVESCREEN.VAS_TRANSACTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.VAS_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.VAS_TRANSACTION
(
  MSISDN        VARCHAR2(20 BYTE)               NOT NULL,
  TIME          DATE                            DEFAULT sysdate,
  PROGRAM_ID    VARCHAR2(50 BYTE),
  CONTENT       VARCHAR2(3000 BYTE),
  LAC           VARCHAR2(20 BYTE),
  CELL_ID       VARCHAR2(20 BYTE),
  SHORT_CODE    VARCHAR2(20 BYTE),
  TITLE         VARCHAR2(256 BYTE),
  MENU_INDEX    NUMBER(5),
  LONGITUDE     NUMBER,
  LATITUDE      NUMBER,
  VAS_TRANS_ID  NUMBER(31)                      NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.TIME IS 'Thoi gian thue bao chon mot menu VAS dang "Chi tiet"';

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.CONTENT IS 'Noi dung chi tiet cua TITLE. Chinh la truong CONTENT trong bang MENU_ITEMS';

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.LAC IS 'Vi tri  LAC cua thue bao luc thuc hien chon xem "Chi tiet"';

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.CELL_ID IS 'Vi tri CELL_ID cua thue bao luc thuc hien chon xem "Chi tiet"';

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.SHORT_CODE IS 'Dau so dich vu. Chinh la truong SHORT_CODE trong bang MENU_ITEMS';

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.TITLE IS 'Chinh la truong TITLE trong bang MENU_ITEMS';

COMMENT ON COLUMN LIVESCREEN.VAS_TRANSACTION.MENU_INDEX IS 'Index cua menu ma thue bao vua chon. Phuc vu cho viec thong ke diem cua TRIVIA';



CREATE INDEX LIVESCREEN.INDEX_ISDN ON LIVESCREEN.VAS_TRANSACTION
(MSISDN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX LIVESCREEN.INDEX_SHORTCODE_DATETIME ON LIVESCREEN.VAS_TRANSACTION
(TIME, SHORT_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.VAS_TRANSACTION_PK ON LIVESCREEN.VAS_TRANSACTION
(VAS_TRANS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.VAS_TRANSACTION_TRG 
BEFORE INSERT
ON LIVESCREEN.VAS_TRANSACTION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column VAS_TRANS_ID
  :new.VAS_TRANS_ID := VAS_TRANSACTION_SEQ.nextval;
END VAS_TRANSACTION_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM VAS_TRANSACTION FOR LIVESCREEN.VAS_TRANSACTION;


ALTER TABLE LIVESCREEN.VAS_TRANSACTION ADD (
  CONSTRAINT VAS_TRANSACTION_PK
  PRIMARY KEY
  (VAS_TRANS_ID)
  USING INDEX LIVESCREEN.VAS_TRANSACTION_PK
  ENABLE VALIDATE);
