DROP TABLE LIVESCREEN.VAS_CDR_TEMP CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.VAS_CDR_TEMP
(
  FILE_ID         NUMBER(10),
  MSG_ID          NUMBER(15),
  MSG_TYPE        NUMBER(5),
  SUBS_MSISDN     VARCHAR2(21 BYTE),
  SERVICE_MSISDN  VARCHAR2(21 BYTE),
  RECEIVE_TIME    DATE,
  DELIVERY_TIME   DATE,
  SMSC_ID         CHAR(30 BYTE),
  SMPP_SERVICE    CHAR(30 BYTE),
  ERR_CODE        NUMBER(5),
  STATUS          NUMBER(5),
  STATUS_DETAIL   VARCHAR2(128 BYTE),
  CONTENT         VARCHAR2(512 BYTE),
  MOVE_STATUS     NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
