ALTER TABLE LIVESCREEN.WELCOME
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.WELCOME CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.WELCOME
(
  MSISDN        VARCHAR2(15 BYTE)               NOT NULL,
  ID            NUMBER(31),
  STATUS        NUMBER(1)                       DEFAULT 0                     NOT NULL,
  STATUS_ID     NUMBER(2),
  COS_ID        VARCHAR2(127 BYTE),
  RESP_TYPE     VARCHAR2(15 BYTE),
  SEND_TIME     DATE                            NOT NULL,
  SENT_TIME     DATE,
  CONTENT       VARCHAR2(3071 BYTE),
  PRIORITY      NUMBER(1),
  MESSAGE_ID    VARCHAR2(100 BYTE),
  ERROR_CODE    NUMBER(10),
  ERROR_DETAIL  VARCHAR2(255 BYTE),
  INSERT_TIME   DATE                            DEFAULT sysdate,
  RETRY         NUMBER
)
TABLESPACE MTPKG
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN LIVESCREEN.WELCOME.ID IS 'Khoa chinh';

COMMENT ON COLUMN LIVESCREEN.WELCOME.STATUS IS '0: pending (Chua xu ly hoac xu ly khong thanh cong), 1: processing (Dang xu ly), 2: done (Xu ly xong)';

COMMENT ON COLUMN LIVESCREEN.WELCOME.STATUS_ID IS 'Tuong ung voi truong STATUS_ID trong bang PROFILE';

COMMENT ON COLUMN LIVESCREEN.WELCOME.COS_ID IS 'Tuong ung voi truong COS_ID trong bang profile';

COMMENT ON COLUMN LIVESCREEN.WELCOME.RESP_TYPE IS 'SMSDD';

COMMENT ON COLUMN LIVESCREEN.WELCOME.SEND_TIME IS 'Thoi gian can gui tin';

COMMENT ON COLUMN LIVESCREEN.WELCOME.SENT_TIME IS 'Thoi gian gui tin thanh cong';

COMMENT ON COLUMN LIVESCREEN.WELCOME.CONTENT IS '*CHUA SU DUNG*Noi dung tin';

COMMENT ON COLUMN LIVESCREEN.WELCOME.PRIORITY IS 'Uu tien gui cac SMS thong bao toi khach hang';

COMMENT ON COLUMN LIVESCREEN.WELCOME.MESSAGE_ID IS '*CHUA SU DUNG* La truong trong ban tin SMPP de map voi ban tin DeliveryReport de nhan biet tin nhan da den thue bao hay chua';

COMMENT ON COLUMN LIVESCREEN.WELCOME.ERROR_CODE IS 'Ma loi do SMSC tra ve';



CREATE INDEX LIVESCREEN.WELCOME_MID_IDX ON LIVESCREEN.WELCOME
(MESSAGE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.WELCOME_MSISDN_IDX ON LIVESCREEN.WELCOME
(MSISDN)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.WELCOME_PK ON LIVESCREEN.WELCOME
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.WELCOME_TRG 
BEFORE INSERT
ON LIVESCREEN.WELCOME
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := WELCOME_SEQ.nextval;
END WELCOME_TRG;
/


ALTER TABLE LIVESCREEN.WELCOME ADD (
  CONSTRAINT WELCOME_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.WELCOME_PK
  ENABLE VALIDATE);
