ALTER TABLE LIVESCREEN.ZONE
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ZONE CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ZONE
(
  ZONE_ID       NUMBER(15),
  ZONE_NAME     VARCHAR2(255 BYTE),
  DESCRIPTION   VARCHAR2(255 BYTE),
  CREATED_DATE  DATE,
  UPDATED_DATE  DATE,
  USER_ID       NUMBER(7),
  STATUS        VARCHAR2(15 BYTE),
  PARENT_ID     NUMBER(15),
  SHAPE         VARCHAR2(4000 BYTE),
  COLOR         VARCHAR2(15 BYTE),
  ZONE_TYPE     NUMBER(1)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.ZONE_PK ON LIVESCREEN.ZONE
(ZONE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX LIVESCREEN.ZONE_U01 ON LIVESCREEN.ZONE
(ZONE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM ZONE FOR LIVESCREEN.ZONE;


ALTER TABLE LIVESCREEN.ZONE ADD (
  CONSTRAINT ZONE_PK
  PRIMARY KEY
  (ZONE_ID)
  USING INDEX LIVESCREEN.ZONE_PK
  ENABLE VALIDATE,
  CONSTRAINT ZONE_U01
  UNIQUE (ZONE_NAME)
  USING INDEX LIVESCREEN.ZONE_U01
  ENABLE VALIDATE);
