ALTER TABLE LIVESCREEN.ZONE_KEYWORD
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ZONE_KEYWORD CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ZONE_KEYWORD
(
  ID         VARCHAR2(100 CHAR),
  ZONE_ID    NUMBER(20),
  ZONE_NAME  VARCHAR2(100 CHAR),
  KEYWORD    VARCHAR2(100 CHAR),
  REGEX      VARCHAR2(100 CHAR)
)
TABLESPACE TBS_PROFILE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.ZONE_KEYWORD_PK ON LIVESCREEN.ZONE_KEYWORD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM ZONE_KEYWORD FOR LIVESCREEN.ZONE_KEYWORD;


ALTER TABLE LIVESCREEN.ZONE_KEYWORD ADD (
  CONSTRAINT ZONE_KEYWORD_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ZONE_KEYWORD_PK
  ENABLE VALIDATE);
