ALTER TABLE LIVESCREEN.ZONE_CELL
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ZONE_CELL CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ZONE_CELL
(
  ID        NUMBER(15),
  CELL_KEY  VARCHAR2(63 BYTE),
  ZONE_ID   NUMBER(15)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.ZONE_CELL_PK ON LIVESCREEN.ZONE_CELL
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.ZONE_CELL_TRG
BEFORE INSERT
ON LIVESCREEN.ZONE_CELL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := ZONE_CELL_SEQ.nextval;
END ZONE_CELL_TRG;
/


CREATE OR REPLACE PUBLIC SYNONYM ZONE_CELL FOR LIVESCREEN.ZONE_CELL;


ALTER TABLE LIVESCREEN.ZONE_CELL ADD (
  CONSTRAINT ZONE_CELL_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ZONE_CELL_PK
  ENABLE VALIDATE);
