DROP TABLE LIVESCREEN.ZONE_USER CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ZONE_USER
(
  ZONE_ID     NUMBER,
  SCREENNAME  VARCHAR2(100 BYTE),
  USERID      NUMBER
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE PUBLIC SYNONYM ZONE_USER FOR LIVESCREEN.ZONE_USER;
