ALTER TABLE LIVESCREEN.ZONE_BSC
 DROP PRIMARY KEY CASCADE;

DROP TABLE LIVESCREEN.ZONE_BSC CASCADE CONSTRAINTS;

CREATE TABLE LIVESCREEN.ZONE_BSC
(
  ID       NUMBER(15),
  BSC_ID   VARCHAR2(31 BYTE),
  ZONE_ID  NUMBER(15)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX LIVESCREEN.ZONE_BSC_PK ON LIVESCREEN.ZONE_BSC
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER LIVESCREEN.ZONE_BSC_TRG
 BEFORE 
 INSERT
 ON LIVESCREEN.ZONE_BSC
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := ZONE_BSC_SEQ.nextval;
END;
/


CREATE OR REPLACE PUBLIC SYNONYM ZONE_BSC FOR LIVESCREEN.ZONE_BSC;


ALTER TABLE LIVESCREEN.ZONE_BSC ADD (
  CONSTRAINT ZONE_BSC_PK
  PRIMARY KEY
  (ID)
  USING INDEX LIVESCREEN.ZONE_BSC_PK
  ENABLE VALIDATE);
