DROP TRIGGER LIVESCREEN.ALERT_CHANNEL_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.ALERT_CHANNEL_TRG 
 BEFORE
  INSERT
 ON LIVESCREEN.ALERT_CHANNEL
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT ALERT_CHANNEL_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
