DROP TRIGGER LIVESCREEN.ALERT_MESSAGE_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.ALERT_MESSAGE_TRG 
 BEFORE
  INSERT
 ON LIVESCREEN.ALERT_MESSAGE
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT ALERT_MESSAGE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
