DROP TRIGGER LIVESCREEN.ALERT_CONFIG_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.ALERT_CONFIG_TRG 
 BEFORE
  INSERT
 ON LIVESCREEN.ALERT_CONFIG
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT ALERT_CONFIG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
