DROP TRIGGER LIVESCREEN.BLACKLIST_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.BLACKLIST_TRG 
 BEFORE
  INSERT
 ON LIVESCREEN.BLACKLIST
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
  SELECT BLACKLIST_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
