DROP TRIGGER LIVESCREEN.BROADCAST_CATEGORY_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.BROADCAST_CATEGORY_TRG BEFORE INSERT ON LIVESCREEN.BROADCAST_CATEGORY 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.CATEGORY_ID IS NULL THEN
      SELECT BROADCAST_CATEGORY_SEQ.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
