DROP TRIGGER LIVESCREEN.BROADCASTTIME_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.BROADCASTTIME_TRG BEFORE INSERT ON LIVESCREEN.BROADCASTTIME 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.BROADCASTTIME_ID IS NULL THEN
      SELECT BROADCASTTIME_SEQ.NEXTVAL INTO :NEW.BROADCASTTIME_ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
