DROP TRIGGER LIVESCREEN.CATEGORY_SCHEDULE_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.CATEGORY_SCHEDULE_TRG BEFORE INSERT ON LIVESCREEN.CATEGORY_SCHEDULE 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
