DROP TRIGGER LIVESCREEN.CBC_TRANSACTION_MAP_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.CBC_TRANSACTION_MAP_TRG BEFORE INSERT ON LIVESCREEN.CBC_TRANSACTION_MAP
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT CBC_TRANSACTION_MAP_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
