DROP TRIGGER LIVESCREEN.MEDIA_CONTENT_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MEDIA_CONTENT_TRG 
BEFORE INSERT ON LIVESCREEN.MEDIA_CONTENT 
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SEQ_ID IS NULL THEN
      SELECT MEDIA_CONTENT_SEQ.NEXTVAL INTO :NEW.SEQ_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
