DROP TRIGGER LIVESCREEN.MODULE_STATUS_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MODULE_STATUS_TRG 
BEFORE INSERT ON LIVESCREEN.MODULE_STATUS
FOR EACH ROW
DISABLE
BEGIN
  SELECT MODULE_STATUS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
