DROP TRIGGER LIVESCREEN.MTPKG_MESSAGE_QUEUE_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_MESSAGE_QUEUE_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_MESSAGE_QUEUE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := MTPKG_MESSAGE_QUEUE_SEQ.nextval;
END MTPKG_MESSAGE_QUEUE_TRG;
/
