DROP TRIGGER LIVESCREEN.MTPKG_DOWNLOAD_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_DOWNLOAD_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_DOWNLOAD
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DOWNLOAD_ID
  :new.DOWNLOAD_ID := MTPKG_DOWNLOAD_SEQ.nextval;
END MTPKG_DOWNLOAD_TRG;
/
