DROP TRIGGER LIVESCREEN.MTPKG_GROUP_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_GROUP_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_GROUP
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PKG_ID
  :new.GROUP_ID := MTPKG_GROUP_SEQ.nextval;
END MTPKG_GROUP_TRG;
/
