DROP TRIGGER LIVESCREEN.MTPKG_PACKAGE_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_PACKAGE_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_PACKAGE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PKG_ID
  :new.PKG_ID := MTPKG_PACKAGE_SEQ.nextval;
END MTPKG_PACKAGE_TRG;
/
