DROP TRIGGER LIVESCREEN.MTPKG_RECOVER_REQ_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_RECOVER_REQ_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_RECOVER_REQ
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column REQ_ID
  :new.REQ_ID := MTPKG_RECOVER_REQ_SEQ.nextval;
END MTPKG_RECOVER_REQ_TRG;
/
