DROP TRIGGER LIVESCREEN.MTPKG_DISCOUNT_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_DISCOUNT_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_DISCOUNT
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column DISCOUNT_ID
  :new.DISCOUNT_ID := MTPKG_DISCOUNT_SEQ.nextval;
END MTPKG_DISCOUNT_TRG;
/
