DROP TRIGGER LIVESCREEN.MTPKG_FEE_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.MTPKG_FEE_TRG
BEFORE INSERT
ON LIVESCREEN.MTPKG_FEE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column FEE_ID
  :new.FEE_ID := MTPKG_FEE_SEQ.nextval;
END MTPKG_FEE_TRG;
/
