DROP TRIGGER LIVESCREEN.OMAP_EVENT_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.OMAP_EVENT_TRG 
BEFORE INSERT ON LIVESCREEN.OMAP_EVENT
FOR EACH ROW
DISABLE
BEGIN
  SELECT OMAP_EVENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
