DROP TRIGGER LIVESCREEN.PLSQL_PROFILER_RUN_OWNER_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.PLSQL_PROFILER_RUN_OWNER_TRG BEFORE INSERT OR UPDATE OF run_owner ON LIVESCREEN.PLSQL_PROFILER_RUNS FOR EACH ROW
WHEN (
new.run_owner IS NULL
      )
BEGIN :new.run_owner := user; END;
/
