DROP TRIGGER LIVESCREEN.TRG_CP_SHORTCODE;

CREATE OR REPLACE TRIGGER LIVESCREEN.TRG_CP_SHORTCODE
 BEFORE 
 INSERT
 ON LIVESCREEN.CP_SHORTCODE
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.CP_SHORTCODE_ID := CP_SHORTCODE_SEQ.nextval;
END;
/
