DROP TRIGGER LIVESCREEN.VAS_TRANSACTION_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.VAS_TRANSACTION_TRG 
BEFORE INSERT
ON LIVESCREEN.VAS_TRANSACTION
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column VAS_TRANS_ID
  :new.VAS_TRANS_ID := VAS_TRANSACTION_SEQ.nextval;
END VAS_TRANSACTION_TRG;
/
