DROP TRIGGER LIVESCREEN.VAS_CDR_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.VAS_CDR_TRG 
BEFORE INSERT
ON LIVESCREEN.VAS_CDR
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column VAS_CDR_ID
  :new.VAS_CDR_ID := VAS_CDR_SEQ.nextval;
END VAS_CDR_TRG;
/
