DROP TRIGGER LIVESCREEN.WELCOME_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.WELCOME_TRG 
BEFORE INSERT
ON LIVESCREEN.WELCOME
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := WELCOME_SEQ.nextval;
END WELCOME_TRG;
/
