DROP TRIGGER LIVESCREEN.ZONE_BSC_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.ZONE_BSC_TRG
 BEFORE 
 INSERT
 ON LIVESCREEN.ZONE_BSC
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := ZONE_BSC_SEQ.nextval;
END;
/
