DROP TRIGGER LIVESCREEN.ZONE_CELL_TRG;

CREATE OR REPLACE TRIGGER LIVESCREEN.ZONE_CELL_TRG
BEFORE INSERT
ON LIVESCREEN.ZONE_CELL
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID
  :new.ID := ZONE_CELL_SEQ.nextval;
END ZONE_CELL_TRG;
/
